Function.prototype.inheritsFrom=function(d){this.prototype=new d;return this.prototype.constructor=this};function isType(d,e){return!d?e===d:typeof e==="string"?d.__proto__.constructor.name==e:d.__proto__.constructor===e}function isSubtype(d,e){return d==undefined?d==e:d.__proto__==undefined?false:d.__proto__.constructor==e?true:isSubtype(d.__proto__,e)}function isString(d){return isSubtype(d,String)}function isNumber(d){return isSubtype(d,Number)}function isFunc(d){return isType(d,Function)}
function isNode(d){return isSubtype(d,Node)}function isFragment(d){return isSubtype(d,DocumentFragment)}Function.prototype.bound=function(d,e){var i=this,j=function(){return i.apply(d,e?e:arguments)};j.toString=function(){return"bound-method of "+d+"."+i.name+"(...) { [code] }"};return j};Function.Empty=Function.__proto__;Function.NotNull=function(d){return d!=null};Function.NotUndefined=function(d){return d!=undefined};Function.NotNullOrUndefined=function(d){return d!=undefined&&d!=null};
Function.ReturnNull=function(){return null};Function.Identity=function(d){return d};Function.IndexFound=function(d){return d>-1};
function Bling(d,e){if(isBling(d))return d;if(this==window||this==Bling)return new Bling(d,e);e=e||document;if(d==undefined)Bling.__init__(this,[]);else if(typeof d=="string")if(d[0]=="<")Bling.__init__(this,[Bling.HTML.parse(d)]);else if(isBling(e)){Bling.__init__(this,[]);var i=this;e.each(function(){Bling.__copy__(i,this.querySelectorAll(d))})}else if(e.querySelectorAll!=undefined)Bling.__init__(this,e.querySelectorAll(d));else throw Error("invalid context "+e+")");else if(typeof d=="number")Array.apply(this,
[d]);else if(d===window||isNode(d))Bling.__init__(this,[d]);else d.length!=undefined?Bling.__init__(this,d):Bling.__init__(this,[d])}Bling.inheritsFrom(Array);function isBling(d){return isType(d,Bling)}Bling.__copy__=function(d,e,i){var j=0;for(i=i?Math.min(e.length,i):e.length;j<i;j++)d.push(e[j])};Bling.__init__=function(d,e){Array.apply(d,[e.length]);Bling.__copy__(d,e)};Bling.operator=Bling;
Bling.extend=function(d,e,i){for(var j in e)if(i&&d[j]!=undefined)for(var l in i)d[j][l]=e[j][l];else d[j]=e[j];return d};Bling.addMethods=function(d){Bling.extend(Bling.prototype,d)};Bling.addGlobals=function(d){d&&Bling.extend(Bling,d)};
Bling.privatescope=function(){function d(a){for(var b=a.cloneNode(),c=0;c<a.childNodes.length;c++)b.appendChild(d(a.childNodes[c])).parentNode=b;return b}function e(a){return function(b){return isFunc(b)?this.bind(a,b):this.trigger(a,b?b:[])}}function i(a,b){throw Error("sql error ["+b.code+"] "+b.message);}var j=new (function(){var a=[],b=function(){a.shift()()};this.schedule=function(c,f){if(isFunc(c)){var g=(new Date).getTime(),h=a.length;c.order=f<g?f+g:f;if(h==0||c.order>a[h-1].order)a[h]=c;
else for(g=0;g<h;g++)a[g].order>c.order&&a.splice(g,0,c);setTimeout(b,f)}}});Bling.addGlobals({dumpText:function(a,b,c){var f="";c=c||{};b=b||"";if(typeof a=="object"){if(c[a])return"{..circular ref..}";c[a]=true;f="{\n";b+="\t";for(var g in a){var h=undefined;try{h=a[g]}catch(k){console.log(g,k)}h=isNode(h)?h.toString():Bling.dumpText(Bling.dumpText(h,b,c));f+=b+g+": "+h+",\n"}b=b.slice(1);f+=b+"}"}else if(typeof a=="string"){if(a.length>250)a=a.substring(0,250)+"...";f+=a[0]!='"'?'"'+a+'"':a}else if(typeof a==
"function"){if(c[a])return"{..circular ref..}";c[a]=true;a=""+a;f+=a.slice(0,a.indexOf("{")+1)+" ... }"}else f+=""+a;return f},dumpHtml:function(a){return Bling.dumpText(a).replace(/(?:\r|\n)+/g,"<br>").replace(/\t/g,"&nbsp;&nbsp;")}});Bling.addMethods({each:function(a){this.forEach(function(b){a.call(b,b)});return this},map:function(a){return new Bling(Array.prototype.map.call(this,function(b){try{return a.call(b,b)}catch(c){if(isType(c,TypeError))return a(b)}}))},reduce:function(a){if(!a||this.length==
0)return null;return Array.prototype.reduce.call(this,function(b,c){return a.apply(c,[b,c])})},filter:function(a){for(var b=new Bling(this.length),c=0,f=this.length;c<f;c++){var g=this[c];a.call(g,g)&&b.push(g)}return b},distinct:function(){var a={};this.each(function(){a[this]=1});var b=new Bling;for(var c in a)b.push(c);return b},zip:function(a){if(!a)return this;var b=a.indexOf(".");return b>-1?this.zip(a.substr(0,b)).zip(a.substr(b+1)):this.map(function(){return typeof this[a]=="function"?this[a].bound(this):
this[a]})},zap:function(a,b){if(!a)return this;var c=a.indexOf(".");return c>-1?this.zip(a.substr(0,c)).zap(a.substr(c+1),b):this.each(function(){this[a]=b})},take:function(a){a=a||1;a=Math.min(a,this.length);for(var b=new Bling(a),c=0;c<a;c++)b.push(this[c]);return b},skip:function(a){a=a||1;for(var b=new Bling(Math.max(0,this.length-a)),c=0,f=this.length-a;c<f;c++)b.push(this[c+a]);return b},last:function(a){return a?this.skip(Math.max(0,this.length-a)):this.skip(this.length-2)[0]},first:function(a){return a?
this.take(a):this[0]},join:function(a){if(this.length==0)return"";return this.reduce(function(b){return b+a+this})},slice:function(a,b){var c=this.length;b=b==undefined?c:b<0?c+b:b;a=a==undefined?c:a<0?c+a:a;return this.take(b).skip(a)},concat:function(a){for(var b=0,c=a.length;b<c;b++)this.push(a[b]);return this},weave:function(a){var b=a.length,c=new Bling(this.length+b);c.length=this.length+b;for(var f=this.length-1;f>=0;f--)c[f*2+1]=this[f];for(f=0;f<b;f++)c[f*2]=a[f];return c},toString:function(){return"Bling{["+
this.map(function(){return this.toString()}).join(", ")+"]}"},floats:function(){return this.map(parseFloat)},ints:function(){return this.map(parseInt)},squares:function(){return this.map(function(){return this*this})},sum:function(){return this.reduce(function(a){return a+this})},max:function(){return this.reduce(Math.max)},min:function(){return this.reduce(Math.min)},average:function(){return this.sum()/this.length},magnitude:function(){return Math.sqrt(this.squares().sum())},scale:function(a){return this.map(function(){return a*
this})},call:function(){return this.apply(null,arguments)},apply:function(a,b){return this.filter(Function.NotNullOrUndefined).map(function(){return this.apply(a,b)})},future:function(a,b){b&&j.schedule(b.bound(this),a);return this},fork:function(a){this.future(0,a.bound(this.clone()));return this},merge:function(){for(var a=new Bling,b=0,c=this.length;b<c;b++)a.concat(this[b]);return a}});var l=function(a,b){a&&b&&a.parentNode.insertBefore(b,a)},n=function(a){return isNode(a)?a:isBling(a)?a.toFragment():
isString(a)?(new Bling(a)).toFragment():isFunc(a.toString)?(new Bling(a.toString())).toFragment():undefined};Bling.addGlobals({HTML:{parse:function(a){var b=document.createElement("div");b.innerHTML=a;a=document.createDocumentFragment();for(var c=0,f=b.childNodes.length;c<f;c++)a.appendChild(b.removeChild(b.childNodes[0]));return f==1?a.removeChild(a.childNodes[0]):a},stringify:function(a){a=d(a);var b=document.createElement("div");b.appendChild(a);var c=b.innerHTML;b.removeChild(a);a.parentNode=
null;return c}},rgb:function a(b){var c=document.createElement("div");c.style.color=b;if(a=c.style.getPropertyValue("color"))return(new Bling(a.slice(a.indexOf("(")+1,a.indexOf(")")).split(", "))).floats();return new Bling}});Bling.addMethods({html:function(a){return a==undefined?this.zip("innerHTML"):isString(a)?this.zap("innerHTML",a):isBling(a)?this.html(a.toFragment()):isNode(a)?this.each(function(){for(this.replaceChild(this.childNodes[0],a);this.childNodes.length>1;)this.removeChild(this.childNodes[1])}):
undefined},append:function(a){a=n(a);this.zip("appendChild").take(1).call(a);this.zip("appendChild").skip(1).each(function(){this(d(a))});return this},appendTo:function(a){(new Bling(a)).append(this);return this},prepend:function(a){a=n(a);this.take(1).each(function(){l(this.childNodes[0],a)});this.skip(1).each(function(){l(this.childNodes[0],d(a))});return this},prependTo:function(a){(new Bling(a)).prepend(this);return this},before:function(a){a=n(a);this.take(1).each(function(){l(this,a)});this.skip(1).each(function(){l(this,
d(a))});return this},after:function(a){a=n(a);this.take(1).each(function(){this.parentNode.insertBefore(a,this.nextSibling)});this.skip(1).each(function(){this.parentNode.insertBefore(d(a),this.nextSibling)});return this},wrap:function(a){a=n(a);if(isFragment(a))throw Error("cannot wrap something with a fragment");return this.map(function(b){if(isFragment(b))a.appendChild(b);else if(isNode(b)){var c=b.parentNode;if(c){var f=document.createElement("dummy");a.appendChild(c.replaceChild(f,b));c.replaceChild(a,
f)}else a.appendChild(b)}return a})},unwrap:function(){return this.each(function(){this.parentNode&&this.parentNode.parentNode&&this.parentNode.parentNode.replaceChild(this.parentNode,this)})},attr:function(a,b){var c=this.zip(b?"setAttribute":"getAttribute").call(a,b);return b?this:c},addClass:function(a){return this.removeClass(a).each(function(){this.className=this.className.split(" ").push(a).join(" ")})},removeClass:function(a){var b=function(c){return c!=a};return this.each(function(){this.className.split(" ").filter(b).join(" ")})},
toggleClass:function(a){var b=function(c){return c!=a};return this.each(function(c){var f=c.className.split(" ");c.className=f.indexOf(a)>-1?f.filter(b).join(" "):f.push(a).join(" ")})},hasClass:function(a){this.zip("className.split").call(" ").zip("indexOf").call(a).map(Function.IndexFound)},text:function(a){return a?this.zap("innerText",a):this.zip("innerText")},val:function(a){return a?this.zap("value",a):this.zip("value")},css:function(a,b){if(b!=undefined&&b!=null){this.zip("style.setProperty").call(a,
b);return this}return this.map(window.getComputedStyle).filter(Function.NotNull).zip("getPropertyValue").call(a)},width:function(){return this.css("width")},height:function(){return this.css("height")},rgb:function(){return this.length==4?"rgba("+this.join(", ")+")":this.length==3?"rgb("+this.join(", ")+")":undefined},child:function(a){return this.map(function(){return this.childNodes[a]})},children:function(){return this.map(function(){return new Bling(this.childNodes)})},parent:function(){return this.zip("parentNode")},
parents:function(){return this.map(function(){for(var a=$([]),b=this.parentNode;b;){a.push(b);b=b.parentNode}return a})},remove:function(){return this.each(function(){if(this.parentNode){this.parentNode.removeChild(this);this.parentNode=null}})},find:function(a){return this.map(function(){return new Bling(a,this)}).reduce(function(b){return b.concat(this)})},clone:function(){return this.map(d)},toFragment:function(){var a=document.createDocumentFragment();this.each(function(b){a.appendChild(isNode(b)?
b:isBling(b)?b.toFragment():isString(b)?(new Bling(b)).toFragment():isFunc(b.toString)?(new Bling(b.toString())).toFragment():undefined)});return a.childNodes.length==1?a.removeChild(a.childNodes[0]):a}});Bling.addGlobals({ready:function(a){(new Bling(window)).bind("load",a)}});Bling.addMethods({bind:function(a,b){return this.each(function(){this.addEventListener(a,b)})},once:function(a,b){var c=function(f){b.apply(this,[f]);this.unbind(a,c)};return this.bind(a,c)},cycle:function(a){var b=0,c=arguments.slice(1,
arguments.length);return this.bind(a,function(f){c[b].apply(this,[f]);b=b++%c.length})},unbind:function(a,b){return this.each(function(){this.removeEventListener(a,b)})},trigger:function(a,b){var c=undefined;b=Bling.extend({bubbles:true,cancelable:true},b);switch(a){case "click":case "mousemove":case "mousedown":case "mouseup":case "mouseover":case "mouseout":c=document.createEvent("MouseEvents");b=Bling.extend({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,shiftKey:false,
metaKey:false,button:0,relatedTarget:null},b);c.initMouseEvent(a,b.bubbles,b.cancelable,window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);break;case "blur":case "focus":case "reset":case "submit":case "abort":case "change":case "load":case "unload":c=document.createEvent("UIEvents");c.initUIEvent(a,b.bubbles,b.cancelable,window,1);break;case "touchstart":case "touchmove":case "touchend":case "touchcancel":c=document.createEvent("TouchEvents");
b=Bling.extend({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,touches:[],targetTouches:[],changedTouches:[],scale:1,rotation:0},b);c.initTouchEvent(a,b.bubbles,b.cancelable,window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.touches,b.targetTouches,b.changedTouches,b.scale,b.rotation);break;case "gesturestart":case "gestureend":case "gesturecancel":c=document.createEvent("GestureEvents");b=Bling.extend({detail:1,
screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,target:null,scale:1,rotation:0},b);c.initGestureEvent(a,b.bubbles,b.cancelable,window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.target,b.scale,b.rotation);break;case "drag":case "drop":case "selection":case "cut":case "copy":case "paste":case "orientationchange":default:c=document.createEvent("Events");c.initEvent(a,b.bubbles,b.cancelable)}return c?this.each(function(){this.dispatchEvent(c);
c.result=c.returnValue=undefined}):this},click:e("click"),mousemove:e("mousemove"),mousedown:e("mousedown"),mouseup:e("mouseup"),mouseover:e("mouseover"),mouseout:e("mouseout"),blur:e("blur"),focus:e("focus"),load:e("load"),ready:e("load"),unload:e("unload"),reset:e("reset"),submit:e("submit"),change:e("change"),abort:e("abort"),cut:e("cut"),copy:e("copy"),paste:e("paste"),selection:e("selection"),drag:e("drag"),drop:e("drop"),orientationchange:e("orientationchange"),touchstart:e("touchstart"),touchmove:e("touchmove"),
touchend:e("touchend"),touchcancel:e("touchcancel"),gesturestart:e("gesturestart"),gestureend:e("gestureend"),gesturecancel:e("gesturecancel")});Bling.addGlobals({duration:function(a){var b={slow:700,medium:500,normal:300,fast:100}[a];return b?b:parseFloat(a)}});Bling.addMethods({transform:function a(b,c,f){if(typeof c=="function"){f=c;c=undefined}c=c||"normal";var g=Bling.duration(c);c=[];var h={};for(var k in b)if(/(?:scale|translate|rotate|scale3d|translateX|translateY|translateZ|translate3d|rotateX|rotateY|rotateZ|rotate3d)/.test(k)){var m=
b[k];if(m.join)m=m.join(", ");if(m.toString)m=m.toString();a+=" "+k+"("+m+")"}else h[k]=b[k];for(k in h)c.push(k);this.css("-webkit-transition-property",c.join(", "));this.css("-webkit-transition-duration",c.map(function(){return g+"ms"}).join(", "));for(k in h)this.css(k,h[k]);return this.future(g,f)},hide:function(a){return this.each(function(){this._display=this.style.display=="none"?undefined:this.style.display;this.style.display="none"}).future(0,a)},show:function(a){return this.each(function(){this.style.display=
this._display?this._display:"";this._display=undefined}).future(0,a)},fadeIn:function(a,b){return this.css("opacity","0.0").show(function(){this.transform({opacity:"1.0",translate3d:[0,0,0]},a,b)})},fadeOut:function(a,b){return this.transform({opacity:"0.0"},a,function(){this.hide();b&&b.call(this)})},fadeLeft:function(a,b){return this.transform({opacity:"0.0",translate3d:["-"+this.width()+"px",0,0]},a,function(){this.hide();b&&b.call(this)})},fadeRight:function(a,b){return this.transform({opacity:"0.0",
translate3d:[this.width()+"px",0,0]},a,function(){this.hide();b&&b.call(this)})},fadeUp:function(a,b){return this.transform({opacity:"0.0",translate3d:[0,"-"+this.height()+"px",0]},a,function(){this.hide();b&&b.call(this)})},fadeDown:function(a,b){return this.transform({opacity:"0.0",translate3d:[0,this.height()+"px",0]},a,function(){this.hide();b&&b.call(this)})}});Bling.addGlobals({db:function(a,b,c,f){return new Bling([window.openDatabase(a||"bling.db",b||"1.0",c||"bling database",f||1024)])}});
Bling.addMethods({transaction:function(a){this.zip("transaction").call(a);return this},sql:function a(a,b,c,f){if(a!=undefined){if(typeof b=="function"){f=c;c=b;b=undefined}b=b||[];c=c||Function.Empty;f=f||i;assert(isType(this[0],"Database"),"can only call .sql() on a bling of Database");return this.transaction(function(g){g.executeSql(a,b,c,f)})}}});var o=function(a){var b=[];a=JSON.parse(JSON.stringify(a));for(var c in a)b.push(c+"="+escape(a[c]));return b.join("&")};Bling.addGlobals({http:function(a,
b){var c=new XMLHttpRequest;if(isFunc(b))b={success:b.bound(c)};b=Bling.extend({method:"GET",data:null,state:Function.Empty,success:Function.Empty,error:Function.Empty,async:true,withCredentials:false},b);b.state=b.state.bound(c);b.success=b.success.bound(c);b.error=b.error.bound(c);if(b.data&&b.method=="GET")a+="?"+o(b.data);else if(b.data&&b.method=="POST")b.data=o(b.data);c.open(b.method,a,b.async);c.withCredentials=b.withCredentials;c.onreadystatechange=function(){b.state&&b.state();if(c.readyState==
4)if(c.status==200)b.success(c.responseText);else b.error&&b.error(c.status,c.statusText)};c.send(b.data);return new Bling([c])},post:function(a,b){if(isFunc(b))b={success:b};b=b||{};b.method="POST";return Bling.http(a,b)},get:function(a,b){if(isFunc(b))b={success:b};b=b||{};b.method="GET";return Bling.http(a,b)}})}();$=Bling.operator;
