<<<<<<< HEAD
var j=null,m=false;function s(d,g,b){for(var c in g)if(b&&d[c]!=undefined)for(var a in b)d[c][a]=g[c][a];else d[c]=g[c];return d}s(Function.prototype,{da:function(d){this.prototype=new d;return this.prototype.constructor=this},h:function(d,g){function b(){return c.apply(d,g?g:arguments)}var c=this;b.toString=function(){return"bound-method of "+d+"."+c.name+"(...) { [code] }"};return b}});
s(window,{cb:function(d,g){return!d?g===d:typeof g==="string"?d.__proto__.constructor.name==g:d.__proto__.constructor===g},bb:function(d,g){return d==j?d==g:d.__proto__==j?m:typeof g==="string"?d.__proto__.constructor.name==g:d.__proto__.constructor==g?true:isSubtype(d.__proto__,g)},ab:function(d){return typeof d=="string"||isSubtype(d,String)},Za:isFinite,Xa:function(d){return typeof d=="function"||isType(d,Function)},Ya:function(d){return d?d.nodeType>0:m},Wa:function(d){return d?d.nodeType==11:
m},Va:function(d){return d?Function.W(d)=="[object Array]"||isSubtype(d,Array):m},$a:function(d){return typeof d=="object"},Ra:function(d){return d!=j}});var w=Object.prototype.toString;Array.t=function(d,g,b){var c=[],a=0,e=d.length;b=b==undefined?e:b<0?e+b:b;for(g=g==undefined?0:g<0?e+g:g;g<b;)c[a++]=d[g++];return c};Number.k=function(d,g){return parseInt(d)+(g|0)+"px"};
s(Function,{s:function(){},la:function(d){return d!=j},ma:function(d){return d!=undefined},T:function(d){return d>-1},oa:function(d){return d&&this},X:function(d){return function(g){return Math.min(d,g)}},U:function(d){return function(g){return Math.max(d,g)}},W:function(d){return w.apply(d)},k:function(d){return function(){return Number.k(this,d)}}});
s(String,{ka:function(d){return d.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\t/g,"&nbsp;&nbsp;")},V:function(d,g,b){for(b=b||" ";d.length<g;)d=b+d;return d},pa:function(){var d=arguments[0],g=arguments[1],b=arguments[2],c=Array.t(arguments,3).join("");return d.substring(0,g)+c+d.substring(b)}});
(function(){function d(h){var l=0,p=h.length,q=[],n=-1,k=-1,o=j;if(!isString(h))if(isFunc(h.toString)){h=h.toString();p=h.length}else throw TypeError("invalid string argument to extract_quoted");for(;l<p;){n=h.indexOf('"',l);o=h.indexOf("'",l);if(n==-1)n=h.length;if(o==-1)o=h.length;o=n==o?[j,-1]:n<o?['"',n]:["'",o];n=o[1];if(n==-1){q.push(h.substring(l));break}q.push(h.substring(l,n));l=o[0];for(k=h.indexOf(l,n+1);h.charAt(k-1)=="\\"&&k<h.length&&k>0;)k=h.indexOf(l,k+1);k=k;if(k==-1)throw Error("unmatched "+
o[0]+" at "+n);q.push(h.substring(n,k+1));l=k+1}return q}function g(h){for(var l=[],p=0,q=0,n=h.length,k=j,o=j;p<n;){k=o=h.substring(p);q=k.match(a);k=k.match(e);k=q==k?[-1,j]:q==j&&k!=j?[k.index,k[0]]:q!=j&&k==j?[q.index,q[0]]:k.index<q.index?[k.index,k[0]]:[q.index,q[0]];q=k[0];if(q>-1){l.push(o.substring(0,q));l.push(k[1]);p+=q+k[1].length}else{l.push(o);break}}return l}var b=/!==|!=|!|\#|\%|\%=|\&|\&\&|\&\&=|&=|\*|\*=|\+|\+=|-|-=|->|\.{1,3}|\/|\/=|:|::|;|<<=|<<|<=|<|===|==|=|>>>=|>>=|>=|>>>|>>|>|\?|@|\[|\]|}|{|\^|\^=|\^\^|\^\^=|\|=|\|\|=|\|\||\||~/g,
c=/\b[Ff]unction\b|\bvar\b|\.prototype\b|\.__proto__\b|\bString\b|\bArray\b|\bNumber\b|\bObject\b|\bbreak\b|\bcase\b|\bcontinue\b|\bdelete\b|\bdo\b|\bif\b|\belse\b|\bfinally\b|\binstanceof\b|\breturn\b|\bthrow\b|\btry\b|\btypeof\b/g,a=/\/\/.*?\n/,e=/\/\*(?:.|\n)*?\*\//,f=/\d+\.*\d*/g;Function.na=function(h,l){if(isFunc(h))h=h.toString();if(!isString(h))throw TypeError("prettyPrint requires a function or string to format");if($("style#pp-injected").length==0){l=s({ob:"#880",yb:"#008",za:"#080",db:"#088",
mb:"#808"},l);var p="<style id='pp-injected'> ",q;for(q in l)p+="pre.pp ."+q+" { color: "+l[q]+"; }";p+="</style>";$("head").append(p)}return"<pre class='pp'>"+$(g(h)).p(function(n,k){return $(d(n)).p(function(o,r){return o.replace(b,"<span class='opr'>$&</span>").replace(f,"<span class='num'>$&</span>").replace(c,"<span class='kwd'>$&</span>").replace(/\t/g,"&nbsp;&nbsp;")+(r?"<span class='str'>"+r+"</span>":"")}).join("")+(k?"<span class='com'>"+k+"</span>":"")}).join("")+"</pre>"}})();
function x(d,g){if(A(d))return d;g=g||document;if(d===undefined)return B(d,g,[]);if(typeof d==="string"){d=d.Hb();if(d[0]=="<")return B(d,g,[G.parse(d)]);if(A(g))return g.reduce(function(c,a){c.R(a.querySelectorAll(d))},B(d,g,[]));if(g.querySelectorAll!=undefined)try{return B(d,g,g.querySelectorAll(d))}catch(b){console.log("err",b,d,g);return j}throw Error("invalid parameters: "+d+", "+g);}if(typeof d==="number")return B(d,g,Array(d));if(d===window||isNode(d))return B(d,g,[d]);if(d.length!=undefined)return B(d,
g,d);return B(d,g,[d])}var G,H,I,J;x.da(Array);function A(d){return isType(d,x)}function B(d,g,b){b.__proto__=x.prototype;b.c=d;b.d=g;return b}function K(){for(var d=0,g=arguments.length;d<g;d++){var b=arguments[d];if(isFunc(b)){if(b.name==j)throw Error("cannot extend with an anonymous method (must have a name)");x.prototype[b.name]=b}else if(isObject(b))s(x.prototype,b);else throw Error("can only extend by an object or function, not:"+typeof b);}}
function L(d,g){var b=g(),c=arguments.callee;c.r.push(d);c[d]=b;K(b)}
L("Core",function(){function d(b){if(isObject(b)&&isNumber(b))return Number(b);return b}var g=new function(){this.i=[];this.next=function(){this.i.length>0&&this.i.shift()()}.h(this);this.ha=function(b,c){if(isFunc(b)){var a=this.i.length;b.r=c+(new Date).getTime();if(a==0||b.r>this.i[a-1].r)this.i[a]=b;else for(var e=0;e<a;e++)this.i[e].r>b.r&&this.i.splice(e,0,b);setTimeout(this.next,c)}}};return{a:function(b){for(var c=-1,a=this.f(),e=j;++c<a;){e=this[c];b.call(e,e)}return this},map:function(b){var c=
this.f(),a=x(c),e=0,f=j;a.d=this;for(a.c=b;e<c;e++){f=this[e];try{a[e]=b.call(f,f)}catch(h){if(isType(h,TypeError))a[e]=b(f);else throw h;}}return a},reduce:function(b,c){if(!b)return this;var a=c,e=this;if(c==j){a=this[0];e=this.j(1)}e.a(function(){a=b.call(this,a,this)});return a},filter:function(b){var c=0,a=-1,e=this.length,f=x(e),h=j;f.d=this;for(f.c=b;c<e;c++)if(h=this[c])if(isFunc(b)&&b.call(h,h)||isString(b)&&h.G&&h.G(b))f[++a]=h;return f},gb:function(b){return this.map(function(){if(this.G)return this.G(b);
return m})},R:function(b){var c=x(),a=0,e=0,f=j;c.d=this.d;c.c=this.c;for(this.a(function(){c[a++]=this});f=b[e++];)c.contains(f)||(c[a++]=f);return c},L:function(b){var c=x(),a=0,e=0,f=this.length,h=b.length;c.d=this.d;c.c=this.c;if(A(b))for(;a<f;a++){if(b.contains(this[a]))c[c.length]=this[a]}else for(a=0;a<f;a++)for(;e<h;e++)if(this[a]==b[e])c[c.length]=this[a];return c},Ea:function(){return this.R(this)},contains:function(b){return this.$(b)>0},$:function(b){if(b==undefined)return this.f();b=
d(b);if(isObject(b)&&isNumber(b))b=Number(b);var c=0;this.a(function(){var a=this;if(isObject(a)&&isNumber(a))a=Number(a);a==b&&c++});return c},b:function(){function b(n){var k;return function(){k=this[n];return isFunc(k)?k.h(this):k}}function c(n){var k=n.indexOf(".");return k>-1?this.b(n.substr(0,k)).b(n.substr(k+1)):this.map(b(n))}switch(arguments.length){case 0:return this;case 1:return c.call(this,arguments[0]);default:var a={},e=x(),f=arguments.length,h=this.length,l=0,p=0,q=j;for(l=0;l<f;l++)a[l]=
c.call(this,arguments[l]);for(l=0;l<h;l++){f={};for(q in a)f[q]=a[q].shift();e[p++]=f}return e}},n:function(b,c){if(!b)return this;var a=b.indexOf(".");return a>-1?this.b(b.substr(0,a)).n(b.substr(a+1),c):isArray(c)?this.a(function(e){e[b]=c[++a]}):this.a(function(){this[b]=c})},m:function(b){b=Math.min(b|0,this.f());var c=x(b),a=-1;c.d=this.d;for(c.c=this.c;++a<b;)c[a]=this[a];return c},j:function(b){b=Math.min(this.f(),Math.max(0,b|0));var c=x(b);i=0;nn=this.f()-b;c.d=this.d;for(c.c=this.c;i<nn;i++)c[i]=
this[i+b];return c},eb:function(b){return b?this.j(this.f()-b):this[this.length-1]},g:function(b){return b?this.m(b):this[0]},join:function(b){if(this.length==0)return"";return this.reduce(function(c){return c+b+this})},slice:function(b,c){var a=x(Array.t(this,b,c));a.d=this.d;a.c=this.c;return a},concat:function(b){for(var c=this.f()-1,a=-1,e=b.length;a<e;)this[++c]=b[++a];return this},S:function(b){var c=b.length,a=this.length,e=x(2*Math.max(a,c));i=a-1;e.d=this.d;for(e.c=this.c;i>=0;i--)e[i*2+
1]=this[i];for(;++i<c;)e[i*2]=b[i];return e},p:function(b){var c=this.f(),a=0,e=x(Math.ceil(c/2)),f=0;e.d=this.d;e.c=this.c;for(f=0;f<c-1;f+=2)e[a++]=b.call(this,this[f],this[f+1]);if(c%2==1)e[a++]=b.call(this,this[c-1],undefined);return e},I:function(){var b=x(),c=this.f(),a=j,e=0,f=0,h=0,l=0;b.d=this.d;for(b.c=this.c;f<c;f++){a=this[f];h=0;for(e=a.length;h<e;)b[l++]=a[h++]}return b},call:function(){return this.apply(j,arguments)},apply:function(b,c){return this.map(function(){if(isFunc(this))return this.apply(b,
c);return this})},toString:function(){return M+"(["+this.map(function(){return this==undefined||this==window?"undefined":this==j?"null":this.toString().replace(/\[object (\w+)\]/,"$1")}).join(", ")+"])"},q:function(b,c){c&&g.ha(c.h(this),b);return this},log:function(b){b?console.log(b,this,this.length+" items"):console.log(this,this.length+" items");return this},f:function(){for(var b=this.length;b>-1&&this[--b]==undefined;);return b+1}}});
L("Html",function(){function d(a,e){a&&e&&a.parentNode.insertBefore(e,a)}function g(a){a=isNode(a)?a:A(a)?a.z():isString(a)?x(a).z():isFunc(a.toString)?x(a.toString()).z():undefined;H=H||1;if(a.ba==j)a.ba=H++;return a}function b(a){for(var e=a.cloneNode(),f=0;f<a.childNodes.length;f++)e.appendChild(b(a.childNodes[f])).parentNode=e;return e}var c=j;G={parse:function(a){var e=document.createElement("div");e.innerHTML=a;a=document.createDocumentFragment();for(var f=0,h=e.childNodes.length;f<h;f++)a.appendChild(e.removeChild(e.childNodes[0]));
return h==1?a.removeChild(a.childNodes[0]):a},stringify:function(a){a=b(a);var e=document.createElement("div");e.appendChild(a);var f=e.innerHTML;e.removeChild(a);a.parentNode=j;return f},escape:function(a){c=c||x("<div>&nbsp;</div>").Z(0);a=c.n("data",a).b("parentNode.innerHTML").g();c.n("data","");return a}};I={aa:function(a){a=a||this;if(isString(a)){var e=document.createElement("div");e.style.display="none";e.style.color=a;$(document.body).append(e);a=window.getComputedStyle(e).getPropertyValue("color");
$(e).remove();if(a){a=a.slice(a.indexOf("(")+1,a.indexOf(")")).split(", ");if(a.length==3)a[3]=1;return x(a).v()}}},ia:function(a){function e(f){f=f.map(Function.X(255)).map(Function.U(0));f[3]=Math.min(1,f[3]);return"rgba("+f.join(", ")+")"}a=a||this;return A(a[0])?a.map(e):e(a)},Ua:function(a){var e=x(4);e[0]=255-a[0];e[1]=255-a[1];e[2]=255-a[2];e[3]=a[3];return e}};return{ca:function(a){return a==undefined?this.b("innerHTML"):isString(a)?this.n("innerHTML",a):A(a)?this.ca(a.z()):isNode(a)?this.a(function(){for(this.replaceChild(this.childNodes[0],
a);this.childNodes.length>1;)this.removeChild(this.childNodes[1])}):undefined},append:function(a){if(a==j)return this;a=g(a);var e=this.b("appendChild");e.m(1).call(a);e.j(1).a(function(){this(b(a))});return this},Y:function(a){if(a==j)return this;x(a).append(this);return this},fa:function(a){if(a==j)return this;a=g(a);this.m(1).a(function(){d(this.childNodes[0],a)});this.j(1).a(function(){d(this.childNodes[0],b(a))});return this},sb:function(a){if(a==j)return this;x(a).fa(this);return this},ua:function(a){if(a==
j)return this;a=g(a);this.m(1).a(function(){d(this,a)});this.j(1).a(function(){d(this,b(a))});return this},ra:function(a){if(a==j)return this;a=g(a);this.m(1).a(function(){this.parentNode.insertBefore(a,this.nextSibling)});this.j(1).a(function(){this.parentNode.insertBefore(b(a),this.nextSibling)});return this},Mb:function(a){a=g(a);if(isFragment(a))throw Error("cannot wrap something with a fragment");return this.map(function(e){if(isFragment(e))a.appendChild(e);else if(isNode(e)){var f=e.parentNode;
if(f){var h=document.createElement("dummy");a.appendChild(f.replaceChild(h,e));f.replaceChild(a,h)}else a.appendChild(e)}return e})},Kb:function(){return this.a(function(){this.parentNode&&this.parentNode.parentNode&&this.parentNode.parentNode.replaceChild(this,this.parentNode)})},replace:function(a){a=g(a);var e=x(),f=-1;this.m(1).a(function(){if(this.parentNode){this.parentNode.replaceChild(a,this);e[++f]=a}});this.j(1).a(function(){if(this.parentNode){var h=b(a);this.parentNode.replaceChild(h,
this);e[++f]=h}});return e},sa:function(a,e){var f=this.b(e?"setAttribute":"getAttribute").call(a,e);return e?this:f},qa:function(a){return this.ga(a).a(function(){var e=this.className.split(" ").filter(function(f){return f&&f!=""});e.push(a);this.className=e.join(" ")})},ga:function(a){function e(f){return f!=a}return this.a(function(){this.className=this.className.split(" ").filter(e).join(" ")})},Cb:function(a){function e(f){return f!=a}return this.a(function(f){var h=f.className.split(" ");f.className=
h.indexOf(a)>-1?h.filter(e).join(" "):h.push(a).join(" ")})},Qa:function(a){return this.b("className.split").call(" ").b("indexOf").call(a).map(Function.T)},text:function(a){return a?this.n("innerText",a):this.b("innerText")},Lb:function(a){return a?this.n("value",a):this.b("value")},e:function(a,e){if(hasValue(e)||isObject(a)){var f=/^-webkit-/,h=this.b("style.setProperty").map(function(){var p=this;return function(q,n){if(f.test(q)){p(q.replace(f,"-moz-"),n);p(q.replace(f,"-o-"),n);p(q.replace(f,
""),n)}p(q,n)}});if(isString(a))h.call(a,e);else for(var l in a)h.call(l,a[l]);return this}h=this.map(window.getComputedStyle).b("getPropertyValue").call(a);return this.b("style").b(a).S(h).p(function(p,q){return p?p:q})},Ca:function(a,e){var f=this.c,h="<style> ",l=$("head");if(isString(a))if(isString(e))h+=f+" { "+a+": "+e+" } ";else throw Error("defaultCss requires a value with a string key");else if(isObject(a)){h+=f+" { ";for(var p in a)h+=p+": "+a[p];h+=" } "}h+="</style>";l.append(h)},rect:function(){return this.b("getBoundingClientRect").call()},
width:function(){return this.rect().b("width")},height:function(a){return a==j?this.rect().b("height"):this.e("height",a)},top:function(a){return a==j?this.rect().b("top"):this.e("top",a)},left:function(a){return a==j?this.rect().b("left"):this.e("left",a)},position:function(a,e){return a==j?this.rect():e==j?this.e("left",Number.k(a)):this.e({top:Number.k(e),left:Number.k(a)})},va:function(a){a=a||"viewport";var e=document.body.clientHeight/2,f=document.body.clientWidth/2;return this.a(function(){var h=
x(this),l=h.height().v().g(),p=h.width().v().g();p=a=="viewport"||a=="horizontal"?document.body.scrollLeft+f-p/2:NaN;y=a=="viewport"||a=="vertical"?document.body.scrollTop+e-l/2:NaN;h.e({position:"absolute",left:isNumber(p)?p+"px":undefined,top:isNumber(y)?y+"px":undefined})})},Ib:function(a,e){function e(f){f[0]+=(this[0]-f[0])*this[3];f[1]+=(this[1]-f[1])*this[3];f[2]+=(this[2]-f[2])*this[3];f[3]=Math.min(1,f[3]+this[3]);return f}a=a||"background-color";return this.O().map(function(){return this.map(window.getComputedStyle).filter(hasValue).b("getPropertyValue").call(a).filter(isString).map(I.aa).reverse().reduce(e,
x([0,0,0,0])).map(I.ia)})},Z:function(a){return this.map(function(){return this.childNodes[a]})},xa:function(){return this.map(function(){return x(this.childNodes,this)})},parent:function(){return this.b("parentNode")},O:function(){return this.map(function(){for(var a=x(),e=-1,f=this;f=f.parentNode;)a[++e]=f;return a})},tb:function(){return this.map(function(){for(var a=x(),e=-1,f=this;f=f.previousSibling;)a[++e]=f;return a})},next:function(){return this.map(function(){for(var a=x(),e=-1,f=this;f=
f.previousSibling;)a[++e]=f;return a})},remove:function(){return this.a(function(){this.parentNode&&this.parentNode.removeChild(this)})},find:function(a){return this.filter("*").map(function(){return x(a,this)}).I()},ya:function(){return this.map(b)},z:function(){if(this.length==1)return g(this[0]);var a=document.createDocumentFragment();this.map(g).map(a.appendChild.h(a));return a}}});
L("Math",function(){return{v:function(){return this.map(function(){if(A(this))return this.v();return parseFloat(this)})},M:function(){return this.map(function(){if(A(this))return this.M();return parseInt(this)})},ub:function(d){d=d||0;return this.M().map(Function.k(d))},min:function(){return this.reduce(function(d){if(A(this))return this.min();return Math.min(this,d)})},max:function(){return this.reduce(function(d){if(A(this))return this.max();return Math.max(this,d)})},ta:function(){return this.F()/
this.length},F:function(){return this.reduce(function(d){if(A(this))return d+this.F();return d+this})},P:function(){return this.map(function(){if(A(this))return this.P();return this*this})},N:function(){var d=this.map(function(){if(A(this))return this.N();return parseFloat(this)});return Math.sqrt(d.P().F())},scale:function(d){return this.map(function(){if(A(this))return this.scale(d);return d*this})},normalize:function(){return this.scale(1/this.N())}}});
L("Event",function(){function d(b){return function(c){return isFunc(c)?this.o(b,c):this.A(b,c?c:{})}}setTimeout(function(){x.prototype.A!=j&&document.readyState=="complete"?x(document).A("ready"):setTimeout(arguments.callee,10)},0);var g=/, */;return{o:function(b,c){var a=0;b=(b||"").split(g);var e=b.length;return this.a(function(){for(;a<e;a++)this.addEventListener(b[a],c)})},Q:function(b,c){var a=0;b=(b||"").split(g);var e=b.length;return this.a(function(){for(;a<e;a++)this.removeEventListener(b[a],
c)})},nb:function(b,c){var a=0;b=(b||"").split(g);for(var e=b.length;a<e;a++)this.o(b[a],function(f){c.call(this,f);this.Q(f.type,arguments.callee)})},Ba:function(b){function c(){var l=0;return function(p){e[l].call(this,p);l=++l%h}}var a=0,e=Array.t(arguments,1,arguments.length);b=(b||"").split(g);for(var f=b.length,h=e.length;a<f;)this.o(b[a++],c());return this},A:function(b,c){var a=undefined,e=0;b=(b||"").split(g);var f=b.length,h=j;for(c=s({bubbles:true,cancelable:true},c);e<f;e++){h=b[e];switch(h){case "click":case "mousemove":case "mousedown":case "mouseup":case "mouseover":case "mouseout":a=
document.createEvent("MouseEvents");c=s({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:m,altKey:m,shiftKey:m,metaKey:m,button:0,relatedTarget:j},c);a.initMouseEvent(h,c.bubbles,c.cancelable,window,c.detail,c.screenX,c.screenY,c.clientX,c.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,c.button,c.relatedTarget);break;case "blur":case "focus":case "reset":case "submit":case "abort":case "change":case "load":case "unload":a=document.createEvent("UIEvents");a.initUIEvent(h,c.bubbles,c.cancelable,
window,1);break;case "touchstart":case "touchmove":case "touchend":case "touchcancel":a=document.createEvent("TouchEvents");c=s({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:m,altKey:m,shiftKey:m,metaKey:m,touches:[],targetTouches:[],changedTouches:[],scale:1,rotation:0},c);a.Ta(h,c.bubbles,c.cancelable,window,c.detail,c.screenX,c.screenY,c.clientX,c.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,c.touches,c.targetTouches,c.changedTouches,c.scale,c.rotation);break;case "gesturestart":case "gestureend":case "gesturecancel":a=
document.createEvent("GestureEvents");c=s({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:m,altKey:m,shiftKey:m,metaKey:m,target:j,scale:1,rotation:0},c);a.Sa(h,c.bubbles,c.cancelable,window,c.detail,c.screenX,c.screenY,c.clientX,c.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,c.target,c.scale,c.rotation);break;default:a=document.createEvent("Events");a.initEvent(h,c.bubbles,c.cancelable)}a&&this.a(function(){this.dispatchEvent(a);a.result=a.returnValue=undefined})}return this},ea:function(b,
c){var a=this.c,e=this.d;x(e).o(b,function(h){x(a,e).L(x(h.target).O().g()).a(function(){h.target=this;c.call(this,h)})});var f=e.B=e.B||{};f[a]=f[a]||{};f[a][b]=f[a][b]||[];f[a][b].push(c)},Da:function(b,c){var a=this.c,e=this.d,f=x(e);h=e.B;if(h==j)return this;var h=e.B[a][b];a=0;for(e=h.length;a<e;a++)if(c==undefined||c==h[a]){f.Q(b,c);h.splice(a,1);e--;a--}},fb:function(b){var c=0,a=Array.t(arguments,1,arguments.length);return this.ea(b,function(e){a[c].call(this,e);c=++c%a.length})},click:function(b){this.e("cursor").L(["auto",
""]).f()>0&&this.e("cursor","pointer");return isFunc(b)?this.o("click",b):this.A("click",b?b:{})},ib:d("mousemove"),hb:d("mousedown"),lb:d("mouseup"),kb:d("mouseover"),jb:d("mouseout"),blur:d("blur"),focus:d("focus"),load:d("load"),vb:d("ready"),Jb:d("unload"),reset:d("reset"),submit:d("submit"),wa:d("change"),abort:d("abort"),Aa:d("cut"),copy:d("copy"),qb:d("paste"),selection:d("selection"),Fa:d("drag"),Ga:d("drop"),pb:d("orientationchange"),Gb:d("touchstart"),Fb:d("touchmove"),Eb:d("touchend"),
Db:d("touchcancel"),Oa:d("gesturestart"),Na:d("gestureend"),Ma:d("gesturecancel")}});
L("Transform",function(){J=function(g){var b={slow:700,medium:500,normal:300,fast:100,instant:0,now:0}[g];return b?b:parseFloat(g)};var d=/(?:scale|translate|rotate|scale3d|translateX|translateY|translateZ|translate3d|rotateX|rotateY|rotateZ|rotate3d)/;return{transform:function(g,b,c){if(typeof b=="function"){c=b;b=undefined}b=b||"normal";var a=J(b);b=[];var e=0,f=0,h=j,l="",p={};for(f in g)if(d.test(f)){h=g[f];if(h.join)h=h.join(", ");else if(h.toString)h=h.toString();l+=" "+f+"("+h+")"}else p[f]=
g[f];for(f in p)b[e++]=f;if(l)b[e++]="-webkit-transfrom";p["-webkit-transition-property"]=b.join(", ");p["-webkit-transition-duration"]=b.map(function(){return a+"ms"}).join(", ");if(l)p["-webkit-transform"]=l;this.e(p);return this.q(a,c)},J:function(g){return this.a(function(){if(this.style){this.C=this.style.display=="none"?undefined:this.style.display;this.style.display="none"}}).q(50,g)},show:function(g){return this.a(function(){if(this.style){this.style.display=this.C?this.C:"block";this.C=undefined}}).q(50,
g)},Bb:function(g){this.S(this.e("display")).p(function(b,c){if(b=="none"){c.style.display=c.D?c.D:"block";c.D=undefined}else{c.D=b;c.style.display="none"}return c}).q(50,g)},Ia:function(g,b){return this.e("opacity","0.0").show(function(){this.transform({opacity:"1.0",ja:[0,0,0]},g,b)})},u:function(g,b,c,a){c=c||0;a=a||0;return this.a(function(e){x(e).transform({opacity:"0.0",ja:[c,a,0]},g,function(){this.J()})}).q(J(g),b)},Ja:function(g,b){return this.u(g,b,"-"+this.width().g(),0)},Ka:function(g,
b){return this.u(g,b,this.width().g(),0)},La:function(g,b){return this.u(g,b,0,"-"+this.height().g())},Ha:function(g,b){return this.u(g,b,0,this.height().g())}}});
L("Http",function(){function d(g){var b=[],c=0;g=JSON.parse(JSON.stringify(g));for(var a in g)b[c++]=a+"="+escape(g[a]);return b.join("&")}s(x,{K:function(g,b){var c=new XMLHttpRequest;if(isFunc(b))b={l:b.h(c)};b=s({method:"GET",data:j,w:Function.s,l:Function.s,error:Function.s,async:true,withCredentials:m},b);b.w=b.w.h(c);b.l=b.l.h(c);b.error=b.error.h(c);if(b.data&&b.method=="GET")g+="?"+d(b.data);else if(b.data&&b.method=="POST")b.data=d(b.data);c.open(b.method,g,b.async);c.withCredentials=b.withCredentials;
c.onreadystatechange=function(){b.w&&b.w();if(c.readyState==4)c.status==200?b.l(c.responseText):b.error(c.status,c.statusText)};c.send(b.data);return x([c])},rb:function(g,b){if(isFunc(b))b={l:b};b=b||{};b.method="POST";return x.K(g,b)},Pa:function(g,b){if(isFunc(b))b={l:b};b=b||{};b.method="GET";return x.K(g,b)}});return{}});
L("Database",function(){function d(g,b){throw Error("sql error ["+b.code+"] "+b.message);}return{transaction:function(g){this.b("transaction").call(g);return this},xb:function g(g,b,c,a){if(g!=undefined){if(typeof b=="function"){a=c;c=b;b=undefined}b=b||[];c=c||Function.s;a=a||d;assert(isType(this[0],"Database"),"can only call .sql() on a bling of Database");return this.transaction(function(e){e.executeSql(g,b,c,a)})}}}});
L("Template",function(){function d(n,k){var o;if(!(o=arguments.callee.H[n])){o=arguments.callee.H;var r;a:{r=[];var t=n.split(/%[\(\/]/),v=-1,u=1,D=t.length;for(r.push(t[0]);u<D;u++){b:{v=t[u];var z=-1,E=1;if(z==j||z==-1)z=v.length;for(var C=0;C<z;C++){if(v.charAt(C)=="(")E+=1;else if(v.charAt(C)==")")E-=1;if(E==0){v=C;break b}}v=-1}if(v==-1){r="Template syntax error: unmatched '%(' in chunk starting at: "+t[u].substring(0,15);break a}key=t[u].substring(0,v);rest=t[u].substring(v);match=b.exec(rest);
if(match==j){r="Template syntax error: invalid type specifier starting at '"+rest+"'";break a}rest=match[4];r.push(key);r.push(match[1]|0);r.push(match[2]|0);r.push(match[3]);r.push(rest)}r=r}o=o[n]=r}o=o;r=[o[0]];u=t=1;for(D=o.length;u<D-4;u+=5){v=o[u];z=o[u+1];E=o[u+2];C=o[u+3];var N=o[u+4],F=k[v];if(F==j)F="missing required value: "+v;switch(C){case "d":r[t++]=""+parseInt(F);break;case "f":r[t++]=parseFloat(F).toFixed(E);break;default:r[t++]=""+F}if(z>0)r[t]=String.V(r[t],z);r[t++]=N}return r.join("")}
function g(n){return $(n.split(/,\s*/)).b("split").call(" ").map(function(){var k=j;return $(this).map(function(){var o=this.valueOf(),r=o.match(c),t=o.match(a),v=o.match(e);o=o.match(f);var u=j;if(r==j||r.length>1)throw Error("Invalid synth expression: "+r);r=r[0];if(r==="+"&&k!=j){k=k.parentNode;return j}t=t!=j?' id="'+t[0].replace(p,"")+'"':"";v=v!=j?' class="'+$(v).b("replace").call(l,"").join(" ")+'"':"";o=o!=j?$(o).b("replace").call(h,"").b("replace").call(q,"").b("split").call("=").I().p(function(D,
z){return" "+D+'="'+z+'"'}).join(""):"";u=G.parse("<"+r+t+v+o+"></"+r+">");k!=j&&k.appendChild(u);return k=u}).g()})}var b=/([0-9#0+-]*)\.*([0-9#+-]*)([diouxXeEfFgGcrsqm])(.*)/;d.H={};var c=/^\s*([A-Za-z+]+)/g,a=/#([^\[.# ]+)/g,e=/\.([^\[.# ]+)/g,f=/\[([^\[.# ]+)=*([^\]]*)\]/g,h=/(?:^\[)|(?:\]$)/g,l=/\./,p=/#/,q=/"/g;return{Ab:function(n){n=s({},n);this.wb=function(k){return d(G.stringify(this.g()),s(n,k))};return this.J()},zb:function(n){return g(n).Y(this)}}});$=x;var M="$";
=======
Object.Extend=function(d,g,c){for(var f in g)if(c&&d[f]!=undefined)for(var a in c)d[f][a]=g[f][a];else d[f]=g[f];return d};Object.Keys=function(d){var g=[],c=0,f;for(f in d)g[c++]=f;return g};Object.Extend(Function.prototype,{inherit:function(d){this.prototype=new d;return this.prototype.constructor=this},bound:function(d,g){function c(){return f.apply(d,g?g:arguments)}var f=this;c.toString=function(){return"bound-method of "+d+"."+f.name+"(...) { [code] }"};return c}});
function Bling(d,g){if(isBling(d))return d;g=g||document;var c=null;if(d==null)c=[];else if(typeof d==="number")c=Array(d);else if(d===window||isNode(d))c=[d];else if(typeof d==="string"){d=d.trimLeft();if(d[0]=="<")c=[Bling.HTML.parse(d)];else if(isBling(g))c=g.reduce(function(a,b){for(var e=b.querySelectorAll(d),h=0,j=e.length;h<j;h++)a.push(e[h]);return a},[]);else if(g.querySelectorAll!=undefined)try{c=g.querySelectorAll(d)}catch(f){throw Error("invalid selector: "+d,f);}else throw Error("invalid context: "+
g);}else c=d;c.__proto__=Bling.prototype;c.selector=d;c.context=g;return c}Bling.inherit(Array);function isBling(d){return isType(d,Bling)}$=Bling;Bling.symbol="$";
Object.Extend(window,{isType:function(d,g){return!d?g===d:typeof g==="string"?d.__proto__.constructor.name==g:d.__proto__.constructor===g},isSubtype:function(d,g){return d==null?d==g:d.__proto__==null?false:typeof g==="string"?d.__proto__.constructor.name==g:d.__proto__.constructor==g?true:isSubtype(d.__proto__,g)},isString:function(d){return typeof d=="string"||isSubtype(d,String)},isNumber:isFinite,isFunc:function(d){return typeof d=="function"||isType(d,Function)},isNode:function(d){return d?d.nodeType>
0:false},isFragment:function(d){return d?d.nodeType==11:false},isArray:function(d){return d?Function.ToString(d)=="[object Array]"||isSubtype(d,Array):false},isObject:function(d){return typeof d=="object"},hasValue:function(d){return d!=null}});var OtoS=Object.prototype.toString;Array.Slice=function(d,g,c){var f=[],a=0,b=d.length;c=c==undefined?b:c<0?b+c:c;for(g=g==undefined?0:g<0?b+g:g;g<c;)f[a++]=d[g++];return f};Number.Px=function(d,g){return parseInt(d)+(g|0)+"px"};
Object.Extend(String,{HtmlEscape:function(d){return d.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\t/g,"&nbsp;&nbsp;")},PadLeft:function(d,g,c){for(c=c||" ";d.length<g;)d=c+d;return d},Splice:function(){var d=arguments[0],g=arguments[1],c=arguments[2],f=Array.Slice(arguments,3).join("");return d.substring(0,g)+f+d.substring(c)}});
Object.Extend(Function,{Empty:function(){},NotNull:function(d){return d!=null},NotUndefined:function(d){return d!=undefined},IndexFound:function(d){return d>-1},ReduceAnd:function(d){return d&&this},UpperLimit:function(d){return function(g){return Math.min(d,g)}},LowerLimit:function(d){return function(g){return Math.max(d,g)}},ToString:function(d){return OtoS.apply(d)},Px:function(d){return function(){return Number.Px(this,d)}},PrettyPrint:function(){function d(j){var k=0,p=j.length,o=[],s=-1,l=-1,
n=null;if(!isString(j))if(isFunc(j.toString)){j=j.toString();p=j.length}else throw TypeError("invalid string argument to extract_quoted");for(;k<p;){s=j;l=k;n=s.indexOf('"',l);l=s.indexOf("'",l);if(n==-1)n=s.length;if(l==-1)l=s.length;n=n==l?[null,-1]:n<l?['"',n]:["'",l];s=n[1];if(s==-1){o.push(j.substring(k));break}o.push(j.substring(k,s));k=j;l=n[0];for(var m=k.indexOf(l,s+1);k.charAt(m-1)=="\\"&&m<k.length&&m>0;)m=k.indexOf(l,m+1);l=m;if(l==-1)throw Error("unmatched "+n[0]+" at "+s);o.push(j.substring(s,
l+1));k=l+1}return o}function g(j){for(var k=[],p=0,o=0,s=j.length,l=null,n=null;p<s;){l=n=j.substring(p);o=l.match(a);l=l.match(b);l=o==l?[-1,null]:o==null&&l!=null?[l.index,l[0]]:o!=null&&l==null?[o.index,o[0]]:l.index<o.index?[l.index,l[0]]:[o.index,o[0]];o=l[0];if(o>-1){k.push(n.substring(0,o));k.push(l[1]);p+=o+l[1].length}else{k.push(n);break}}return k}var c=/!==|!=|!|\#|\%|\%=|\&|\&\&|\&\&=|&=|\*|\*=|\+|\+=|-|-=|->|\.{1,3}|\/|\/=|:|::|;|<<=|<<|<=|<|===|==|=|>>>=|>>=|>=|>>>|>>|>|\?|@|\[|\]|}|{|\^|\^=|\^\^|\^\^=|\|=|\|\|=|\|\||\||~/g,
f=/\b[Ff]unction\b|\bvar\b|\.prototype\b|\.__proto__\b|\bString\b|\bArray\b|\bNumber\b|\bObject\b|\bbreak\b|\bcase\b|\bcontinue\b|\bdelete\b|\bdo\b|\bif\b|\belse\b|\bfinally\b|\binstanceof\b|\breturn\b|\bthrow\b|\btry\b|\btypeof\b|\btrue\b|\bfalse\b/g,a=/\/\/.*?\n/,b=/\/\*(?:.|\n)*?\*\//,e=/\d+\.*\d*/g,h=/\$\(/g;return function(j,k){if(isFunc(j))j=j.toString();if(!isString(j))throw TypeError("prettyPrint requires a function or string to format");if($("style#pp-injected").length==0){k=Object.Extend({opr:"#880",
str:"#008",com:"#080",kwd:"#088",num:"#808",bln:"#800"},k);var p="pre.pp .bln { font-size: 17px; } ",o;for(o in k)p+="pre.pp ."+o+" { color: "+k[o]+"; }";$("head").append($.synth("style#pp-injected").text(p))}return"<pre class='pp'>"+$(g(j)).fold(function(s,l){return $(d(s)).fold(function(n,m){return n.replace(c,"<span class='opr'>$&</span>").replace(e,"<span class='num'>$&</span>").replace(f,"<span class='kwd'>$&</span>").replace(h,"<span class='bln'>$$</span>(").replace(/\t/g,"&nbsp;&nbsp;")+(m?
"<span class='str'>"+m+"</span>":"")}).join("")+(l?"<span class='com'>"+l+"</span>":"")}).join("")+"</pre>"}}()});Bling.addOps=function(){for(var d=0,g=arguments.length;d<g;d++){var c=arguments[d];if(isFunc(c))if(c.name==null)throw Error("cannot add an anonymous method (must have a name)");else Bling.prototype[c.name]=c;else if(isObject(c))Object.Extend(Bling.prototype,c);else throw Error("can only add an object or function, not:"+typeof c);}};
Bling.module=function(d,g){var c=g(),f=arguments.callee;f.order.push(d);f[d]=c;Bling.addOps(c)};Bling.module.order=[];
Bling.module("Core",function(){function d(a){if(isObject(a)&&isNumber(a))return Number(a);return a}function g(a){var b;return function(){b=this[a];return isFunc(b)?b.bound(this):b}}function c(a){var b=a.indexOf(".");return b>-1?this.zip(a.substr(0,b)).zip(a.substr(b+1)):this.map(g(a))}var f=new function(){this.queue=[];this.next=function(){this.queue.length>0&&this.queue.shift()()}.bound(this);this.schedule=function(a,b){if(isFunc(a)){var e=this.queue.length;a.order=b+(new Date).getTime();if(e==0||
a.order>this.queue[e-1].order)this.queue[e]=a;else for(var h=0;h<e;h++)this.queue[h].order>a.order&&this.queue.splice(h,0,a);setTimeout(this.next,b)}}};return{each:function(a){for(var b=-1,e=this.len(),h=null;++b<e;){h=this[b];a.call(h,h)}return this},map:function(a){var b=this.len(),e=Bling(b),h=0,j=null,k=true;e.context=this;for(e.selector=a;h<b;h++){j=this[h];if(k)try{e[h]=a.call(j,j)}catch(p){if(isType(p,TypeError)){k=false;h--}else e[h]=p}else try{e[h]=a(j)}catch(o){e[h]=o}}return e},reduce:function(a,
b){if(!a)return this;var e=b,h=this;if(b==null){e=this[0];h=this.skip(1)}h.each(function(){e=a.call(this,e,this)});return e},filter:function(a){var b=0,e=-1,h=this.length,j=Bling(h),k=null;j.context=this;for(j.selector=a;b<h;b++)if(k=this[b])if(isFunc(a)&&a.call(k,k)||isString(a)&&k.webkitMatchesSelector&&k.webkitMatchesSelector(a)||isType(a,RegExp)&&a.test(k))j[++e]=k;return j},matches:function(a){if(isType(a,RegExp))return this.map(function(){return a.test(this)});return isString(a)&&this.webkitMatchesSelector?
this.map(function(){return this.webkitMatchesSelector(a)}):this.map(function(){return false})},union:function(a){var b=Bling(),e=0,h=0,j=null;b.context=this.context;b.selector=this.selector;for(this.each(function(){b[e++]=this});j=a[h++];)b.contains(j)||(b[e++]=j);return b},intersect:function(a){var b=Bling(),e=0,h=0,j=this.length,k=a.length;b.context=this.context;b.selector=this.selector;if(isBling(a))for(;e<j;e++){if(a.contains(this[e]))b[b.length]=this[e]}else for(e=0;e<j;e++)for(;h<k;h++)if(this[e]==
a[h])b[b.length]=this[e];return b},distinct:function(){return this.union(this)},contains:function(a){return this.count(a)>0},count:function(a){if(a==undefined)return this.len();a=d(a);if(isObject(a)&&isNumber(a))a=Number(a);var b=0;this.each(function(){var e=this;if(isObject(e)&&isNumber(e))e=Number(e);e==a&&b++});return b},zip:function(){switch(arguments.length){case 0:return this;case 1:return c.call(this,arguments[0]);default:var a={},b=Bling(),e=arguments.length,h=this.length,j=0,k=0,p=null;for(j=
0;j<e;j++)a[j]=c.call(this,arguments[j]);for(j=0;j<h;j++){e={};for(p in a)e[p]=a[p].shift();b[k++]=e}return b}},zap:function(a,b){if(!a)return this;var e=a.indexOf(".");return e>-1?this.zip(a.substr(0,e)).zap(a.substr(e+1),b):isArray(b)?this.each(function(h){h[a]=b[++e]}):this.each(function(){this[a]=b})},take:function(a){a=Math.min(a|0,this.len());var b=Bling(a),e=-1;b.context=this.context;for(b.selector=this.selector;++e<a;)b[e]=this[e];return b},skip:function(a){a=Math.min(this.len(),Math.max(0,
a|0));var b=Bling(a);i=0;nn=this.len()-a;b.context=this.context;for(b.selector=this.selector;i<nn;i++)b[i]=this[i+a];return b},last:function(a){return a?this.skip(this.len()-a):this[this.length-1]},first:function(a){return a?this.take(a):this[0]},join:function(a){if(this.length==0)return"";return this.reduce(function(b){return b+a+this})},slice:function(a,b){var e=Bling(Array.Slice(this,a,b));e.context=this.context;e.selector=this.selector;return e},concat:function(a){for(var b=this.len()-1,e=-1,
h=a.length;e<h;)this[++b]=a[++e];return this},push:function(a){Array.prototype.push.call(this,a);return this},weave:function(a){var b=a.length,e=this.length,h=Bling(2*Math.max(e,b));i=e-1;h.context=this.context;for(h.selector=this.selector;i>=0;i--)h[i*2+1]=this[i];for(;++i<b;)h[i*2]=a[i];return h},fold:function(a){var b=this.len(),e=0,h=Bling(Math.ceil(b/2)),j=0;h.context=this.context;h.selector=this.selector;for(j=0;j<b-1;j+=2)h[e++]=a.call(this,this[j],this[j+1]);if(b%2==1)h[e++]=a.call(this,this[b-
1],undefined);return h},flatten:function(){var a=Bling(),b=this.len(),e=null,h=0,j=0,k=0,p=0;a.context=this.context;for(a.selector=this.selector;j<b;j++){e=this[j];k=0;for(h=e.length;k<h;)a[p++]=e[k++]}return a},call:function(){return this.apply(null,arguments)},apply:function(a,b){return this.map(function(){if(isFunc(this))return this.apply(a,b);return this})},toString:function(){return Bling.symbol+"(["+this.map(function(){return this==undefined||this==window?"undefined":this==null?"null":this.toString().replace(/\[object (\w+)\]/,
"$1")}).join(", ")+"])"},future:function(a,b){b&&f.schedule(b.bound(this),a);return this},log:function(a){a?console.log(a,this,this.length+" items"):console.log(this,this.length+" items");return this},len:function(){for(var a=this.length;a>-1&&this[--a]==undefined;);return a+1}}});
Bling.module("Html",function(){function d(a,b){a&&b&&a.parentNode.insertBefore(b,a)}function g(a){a=isNode(a)?a:isBling(a)?a.toFragment():isString(a)?Bling(a).toFragment():isFunc(a.toString)?Bling(a.toString()).toFragment():undefined;Bling.nextguid=Bling.nextguid||1;if(a.guid==null)a.guid=Bling.nextguid++;return a}function c(a){for(var b=a.cloneNode(),e=0;e<a.childNodes.length;e++)b.appendChild(c(a.childNodes[e])).parentNode=b;return b}var f=null;Bling.HTML={parse:function(a){var b=document.createElement("body");
b.innerHTML=a;a=document.createDocumentFragment();for(var e=0,h=b.childNodes.length;e<h;e++)a.appendChild(b.removeChild(b.childNodes[0]));return h==1?a.removeChild(a.childNodes[0]):a},stringify:function(a){a=c(a);var b=document.createElement("div");b.appendChild(a);var e=b.innerHTML;b.removeChild(a);a.parentNode=null;return e},escape:function(a){f=f||Bling("<div>&nbsp;</div>").child(0);a=f.zap("data",a).zip("parentNode.innerHTML").first();f.zap("data","");return a}};Bling.Color={fromCss:function(a){a=
a||this;if(isString(a)){var b=document.createElement("div");b.style.display="none";b.style.color=a;$(document.body).append(b);a=window.getComputedStyle(b).getPropertyValue("color");$(b).remove();if(a){a=a.slice(a.indexOf("(")+1,a.indexOf(")")).split(", ");if(a.length==3)a[3]=1;return Bling(a).floats()}}},toCss:function(a){function b(e){e=e.map(Function.UpperLimit(255)).map(Function.LowerLimit(0));e[3]=Math.min(1,e[3]);return"rgba("+e.join(", ")+")"}a=a||this;return isBling(a[0])?a.map(b):b(a)},invert:function(a){var b=
Bling(4);b[0]=255-a[0];b[1]=255-a[1];b[2]=255-a[2];b[3]=a[3];return b}};return{html:function(a){return a==undefined?this.zip("innerHTML"):isString(a)?this.zap("innerHTML",a):isBling(a)?this.html(a.toFragment()):isNode(a)?this.each(function(){for(this.replaceChild(this.childNodes[0],a);this.childNodes.length>1;)this.removeChild(this.childNodes[1])}):undefined},append:function(a){if(a==null)return this;a=g(a);var b=this.zip("appendChild");b.take(1).call(a);b.skip(1).each(function(){this(c(a))});return this},
appendTo:function(a){if(a==null)return this;Bling(a).append(this);return this},prepend:function(a){if(a==null)return this;a=g(a);this.take(1).each(function(){d(this.childNodes[0],a)});this.skip(1).each(function(){d(this.childNodes[0],c(a))});return this},prependTo:function(a){if(a==null)return this;Bling(a).prepend(this);return this},before:function(a){if(a==null)return this;a=g(a);this.take(1).each(function(){d(this,a)});this.skip(1).each(function(){d(this,c(a))});return this},after:function(a){if(a==
null)return this;a=g(a);this.take(1).each(function(){this.parentNode.insertBefore(a,this.nextSibling)});this.skip(1).each(function(){this.parentNode.insertBefore(c(a),this.nextSibling)});return this},wrap:function(a){a=g(a);if(isFragment(a))throw Error("cannot wrap something with a fragment");return this.map(function(b){if(isFragment(b))a.appendChild(b);else if(isNode(b)){var e=b.parentNode;if(e){var h=document.createElement("dummy");a.appendChild(e.replaceChild(h,b));e.replaceChild(a,h)}else a.appendChild(b)}return b})},
unwrap:function(){return this.each(function(){this.parentNode&&this.parentNode.parentNode&&this.parentNode.parentNode.replaceChild(this,this.parentNode)})},replace:function(a){a=g(a);var b=Bling(),e=-1;this.take(1).each(function(){if(this.parentNode){this.parentNode.replaceChild(a,this);b[++e]=a}});this.skip(1).each(function(){if(this.parentNode){var h=c(a);this.parentNode.replaceChild(h,this);b[++e]=h}});return b},attr:function(a,b){var e=this.zip(b?"setAttribute":"getAttribute").call(a,b);return b?
this:e},addClass:function(a){return this.removeClass(a).each(function(){var b=this.className.split(" ").filter(function(e){return e&&e!=""});b.push(a);this.className=b.join(" ")})},removeClass:function(a){var b=function(e){return e!=a};return this.each(function(){this.className=this.className.split(" ").filter(b).join(" ")})},toggleClass:function(a){function b(e){return e!=a}return this.each(function(e){var h=e.className.split(" ");e.className=h.indexOf(a)>-1?h.filter(b).join(" "):h.push(a).join(" ")})},
hasClass:function(a){return this.zip("className.split").call(" ").zip("indexOf").call(a).map(Function.IndexFound)},text:function(a){return a?this.zap("innerText",a):this.zip("innerText")},val:function(a){return a?this.zap("value",a):this.zip("value")},css:function(a,b){if(hasValue(b)||isObject(a)){var e=/^-webkit-/,h=this.zip("style.setProperty").map(function(){var k=this;return function(p,o){if(e.test(p)){k(p.replace(e,"-moz-"),o);k(p.replace(e,"-o-"),o);k(p.replace(e,""),o)}k(p,o)}});if(isString(a))h.call(a,
b);else for(var j in a)h.call(j,a[j]);return this}h=this.map(window.getComputedStyle).zip("getPropertyValue").call(a);return this.zip("style").zip(a).weave(h).fold(function(k,p){return k?k:p})},defaultCss:function(a,b){var e=this.selector,h="<style> ",j=$("head");if(isString(a))if(isString(b))h+=e+" { "+a+": "+b+" } ";else throw Error("defaultCss requires a value with a string key");else if(isObject(a)){h+=e+" { ";for(var k in a)h+=k+": "+a[k];h+=" } "}h+="</style>";j.append(h)},rect:function(){return this.zip("getBoundingClientRect").call()},
width:function(){return this.rect().zip("width")},height:function(a){return a==null?this.rect().zip("height"):this.css("height",a)},top:function(a){return a==null?this.rect().zip("top"):this.css("top",a)},left:function(a){return a==null?this.rect().zip("left"):this.css("left",a)},position:function(a,b){return a==null?this.rect():b==null?this.css("left",Number.Px(a)):this.css({top:Number.Px(b),left:Number.Px(a)})},center:function(a){a=a||"viewport";var b=document.body.clientHeight/2,e=document.body.clientWidth/
2;return this.each(function(){var h=Bling(this),j=h.height().floats().first(),k=h.width().floats().first();k=a=="viewport"||a=="horizontal"?document.body.scrollLeft+e-k/2:NaN;y=a=="viewport"||a=="vertical"?document.body.scrollTop+b-j/2:NaN;h.css({position:"absolute",left:isNumber(k)?k+"px":undefined,top:isNumber(y)?y+"px":undefined})})},trueColor:function(a,b){function b(e){e[0]+=(this[0]-e[0])*this[3];e[1]+=(this[1]-e[1])*this[3];e[2]+=(this[2]-e[2])*this[3];e[3]=Math.min(1,e[3]+this[3]);return e}
a=a||"background-color";return this.parents().map(function(){return this.map(window.getComputedStyle).filter(hasValue).zip("getPropertyValue").call(a).filter(isString).map(Bling.Color.fromCss).reverse().reduce(b,Bling([0,0,0,0])).map(Bling.Color.toCss)})},child:function(a){return this.map(function(){return this.childNodes[a]})},children:function(){return this.map(function(){return Bling(this.childNodes,this)})},parent:function(){return this.zip("parentNode")},parents:function(){return this.map(function(){for(var a=
Bling(),b=-1,e=this;e=e.parentNode;)a[++b]=e;return a})},prev:function(){return this.map(function(){for(var a=Bling(),b=-1,e=this;e=e.previousSibling;)a[++b]=e;return a})},next:function(){return this.map(function(){for(var a=Bling(),b=-1,e=this;e=e.previousSibling;)a[++b]=e;return a})},remove:function(){return this.each(function(){this.parentNode&&this.parentNode.removeChild(this)})},find:function(a){return this.filter("*").map(function(){return Bling(a,this)}).flatten()},clone:function(){return this.map(c)},
toFragment:function(){if(this.length==1)return g(this[0]);var a=document.createDocumentFragment();this.map(g).map(a.appendChild.bound(a));return a}}});
Bling.module("Math",function(){return{floats:function(){return this.map(function(){if(isBling(this))return this.floats();return parseFloat(this)})},ints:function(){return this.map(function(){if(isBling(this))return this.ints();return parseInt(this)})},px:function(d){d=d||0;return this.ints().map(Function.Px(d))},min:function(){return this.reduce(function(d){if(isBling(this))return this.min();return Math.min(this,d)})},max:function(){return this.reduce(function(d){if(isBling(this))return this.max();
return Math.max(this,d)})},average:function(){return this.sum()/this.length},sum:function(){return this.reduce(function(d){if(isBling(this))return d+this.sum();return d+this})},squares:function(){return this.map(function(){if(isBling(this))return this.squares();return this*this})},magnitude:function(){var d=this.map(function(){if(isBling(this))return this.magnitude();return parseFloat(this)});return Math.sqrt(d.squares().sum())},scale:function(d){return this.map(function(){if(isBling(this))return this.scale(d);
return d*this})},normalize:function(){return this.scale(1/this.magnitude())}}});
Bling.module("Event",function(){function d(c){eval("f = function "+c+"(f) { // ."+c+"([f]) - trigger [or bind] the '"+c+"' event \nreturn isFunc(f) ? this.bind('"+c+"',f) : this.trigger(e, f ? f : {}) }");return null}setTimeout(function(){Bling.prototype.trigger!=null&&document.readyState=="complete"?Bling(document).trigger("ready"):setTimeout(arguments.callee,20)},0);var g=/, */;return{bind:function(c,f){var a=0;c=(c||"").split(g);var b=c.length;return this.each(function(){for(;a<b;a++)this.addEventListener(c[a],
f)})},unbind:function(c,f){var a=0;c=(c||"").split(g);var b=c.length;return this.each(function(){for(;a<b;a++)this.removeEventListener(c[a],f)})},once:function(c,f){var a=0;c=(c||"").split(g);for(var b=c.length;a<b;a++)this.bind(c[a],function(e){f.call(this,e);this.unbind(e.type,arguments.callee)})},cycle:function(c){function f(){var j=0;return function(k){b[j].call(this,k);j=++j%h}}var a=0,b=Array.Slice(arguments,1,arguments.length);c=(c||"").split(g);for(var e=c.length,h=b.length;a<e;)this.bind(c[a++],
f());return this},trigger:function(c,f){var a=undefined,b=0;c=(c||"").split(g);var e=c.length,h=null;for(f=Object.Extend({bubbles:true,cancelable:true},f);b<e;b++){h=c[b];switch(h){case "click":case "mousemove":case "mousedown":case "mouseup":case "mouseover":case "mouseout":a=document.createEvent("MouseEvents");f=Object.Extend({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,button:0,relatedTarget:null},f);a.initMouseEvent(h,f.bubbles,f.cancelable,
window,f.detail,f.screenX,f.screenY,f.clientX,f.clientY,f.ctrlKey,f.altKey,f.shiftKey,f.metaKey,f.button,f.relatedTarget);break;case "blur":case "focus":case "reset":case "submit":case "abort":case "change":case "load":case "unload":a=document.createEvent("UIEvents");a.initUIEvent(h,f.bubbles,f.cancelable,window,1);break;case "touchstart":case "touchmove":case "touchend":case "touchcancel":a=document.createEvent("TouchEvents");f=Object.Extend({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,
altKey:false,shiftKey:false,metaKey:false,touches:[],targetTouches:[],changedTouches:[],scale:1,rotation:0},f);a.initTouchEvent(h,f.bubbles,f.cancelable,window,f.detail,f.screenX,f.screenY,f.clientX,f.clientY,f.ctrlKey,f.altKey,f.shiftKey,f.metaKey,f.touches,f.targetTouches,f.changedTouches,f.scale,f.rotation);break;case "gesturestart":case "gestureend":case "gesturecancel":a=document.createEvent("GestureEvents");f=Object.Extend({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,
shiftKey:false,metaKey:false,target:null,scale:1,rotation:0},f);a.initGestureEvent(h,f.bubbles,f.cancelable,window,f.detail,f.screenX,f.screenY,f.clientX,f.clientY,f.ctrlKey,f.altKey,f.shiftKey,f.metaKey,f.target,f.scale,f.rotation);break;default:a=document.createEvent("Events");a.initEvent(h,f.bubbles,f.cancelable)}a&&this.each(function(){this.dispatchEvent(a);a.result=a.returnValue=undefined})}return this},live:function(c,f){var a=this.selector,b=this.context;Bling(b).bind(c,function(h){Bling(a,
b).intersect(Bling(h.target).parents().first()).each(function(){h.target=this;f.call(this,h)})});var e=b.__livers__=b.__livers__||{};e[a]=e[a]||{};e[a][c]=e[a][c]||[];e[a][c].push(f)},die:function(c,f){var a=this.selector,b=this.context,e=Bling(b);h=b.__livers__;if(h==null)return this;var h=b.__livers__[a][c];a=0;for(b=h.length;a<b;a++)if(f==undefined||f==h[a]){e.unbind(c,f);h.splice(a,1);b--;a--}},liveCycle:function(c){var f=0,a=Array.Slice(arguments,1,arguments.length);return this.live(c,function(b){a[f].call(this,
b);f=++f%a.length})},click:function(c){this.css("cursor").intersect(["auto",""]).len()>0&&this.css("cursor","pointer");return isFunc(c)?this.bind("click",c):this.trigger("click",c?c:{})},mousemove:d("mousemove"),mousedown:d("mousedown"),mouseup:d("mouseup"),mouseover:d("mouseover"),mouseout:d("mouseout"),blur:d("blur"),focus:d("focus"),load:d("load"),ready:d("ready"),unload:d("unload"),reset:d("reset"),submit:d("submit"),change:d("change"),abort:d("abort"),cut:d("cut"),copy:d("copy"),paste:d("paste"),
selection:d("selection"),drag:d("drag"),drop:d("drop"),orientationchange:d("orientationchange"),touchstart:d("touchstart"),touchmove:d("touchmove"),touchend:d("touchend"),touchcancel:d("touchcancel"),gesturestart:d("gesturestart"),gestureend:d("gestureend"),gesturecancel:d("gesturecancel")}});
Bling.module("Transform",function(){Bling.duration=function(g){var c={slow:700,medium:500,normal:300,fast:100,instant:0,now:0}[g];return c?c:parseFloat(g)};var d=/(?:scale|translate|rotate|scale3d|translateX|translateY|translateZ|translate3d|rotateX|rotateY|rotateZ|rotate3d)/;return{transform:function(g,c,f){if(typeof c=="function"){f=c;c=undefined}c=c||"normal";var a=Bling.duration(c);c=[];var b=0,e=0,h=null,j="",k={};for(e in g)if(d.test(e)){h=g[e];if(h.join)h=h.join(", ");else if(h.toString)h=
h.toString();j+=" "+e+"("+h+")"}else k[e]=g[e];for(e in k)c[b++]=e;if(j)c[b++]="-webkit-transfrom";k["-webkit-transition-property"]=c.join(", ");k["-webkit-transition-duration"]=c.map(function(){return a+"ms"}).join(", ");if(j)k["-webkit-transform"]=j;this.css(k);return this.future(a,f)},hide:function(g){return this.each(function(){if(this.style){this._display=this.style.display=="none"?undefined:this.style.display;this.style.display="none"}}).future(50,g)},show:function(g){return this.each(function(){if(this.style){this.style.display=
this._display?this._display:"block";this._display=undefined}}).future(50,g)},toggle:function(g){this.weave(this.css("display")).fold(function(c,f){if(c=="none"){f.style.display=f._old_display?f._old_display:"block";f._old_display=undefined}else{f._old_display=c;f.style.display="none"}return f}).future(50,g)},fadeIn:function(g,c){return this.css("opacity","0.0").show(function(){this.transform({opacity:"1.0",translate3d:[0,0,0]},g,c)})},fadeOut:function(g,c,f,a){f=f||0;a=a||0;return this.each(function(b){Bling(b).transform({opacity:"0.0",
translate3d:[f,a,0]},g,function(){this.hide()})}).future(Bling.duration(g),c)},fadeLeft:function(g,c){return this.fadeOut(g,c,"-"+this.width().first(),0)},fadeRight:function(g,c){return this.fadeOut(g,c,this.width().first(),0)},fadeUp:function(g,c){return this.fadeOut(g,c,0,"-"+this.height().first())},fadeDown:function(g,c){return this.fadeOut(g,c,0,this.height().first())}}});
Bling.module("Http",function(){function d(g){var c=[],f=0;g=JSON.parse(JSON.stringify(g));for(var a in g)c[f++]=a+"="+escape(g[a]);return c.join("&")}Object.Extend(Bling,{http:function(g,c){var f=new XMLHttpRequest;if(isFunc(c))c={success:c.bound(f)};c=Object.Extend({method:"GET",data:null,state:Function.Empty,success:Function.Empty,error:Function.Empty,async:true,withCredentials:false},c);c.state=c.state.bound(f);c.success=c.success.bound(f);c.error=c.error.bound(f);if(c.data&&c.method=="GET")g+=
"?"+d(c.data);else if(c.data&&c.method=="POST")c.data=d(c.data);f.open(c.method,g,c.async);f.withCredentials=c.withCredentials;f.onreadystatechange=function(){c.state&&c.state();if(f.readyState==4)f.status==200?c.success(f.responseText):c.error(f.status,f.statusText)};f.send(c.data);return Bling([f])},post:function(g,c){if(isFunc(c))c={success:c};c=c||{};c.method="POST";return Bling.http(g,c)},get:function(g,c){if(isFunc(c))c={success:c};c=c||{};c.method="GET";return Bling.http(g,c)}});return{}});
Bling.module("Database",function(){function d(g,c){throw Error("sql error ["+c.code+"] "+c.message);}Bling.db=function(g,c,f,a){return Bling([window.openDatabase(g||"bling.db",c||"1.0",f||"bling database",a||1024)])};return{transaction:function(g){this.zip("transaction").call(g);return this},sql:function g(g,c,f,a){if(g!=undefined){if(typeof c=="function"){a=f;f=c;c=undefined}c=c||[];f=f||Function.Empty;a=a||d;assert(isType(this[0],"Database"),"can only call .sql() on a bling of Database");return this.transaction(function(b){b.executeSql(g,
c,f,a)})}}}});
Bling.module("Template",function(){function d(l){var n=[];l=l.split(/%[\(\/]/);var m=-1,q=1,v=l.length;for(n.push(l[0]);q<v;q++){a:{m=l[q];var r=-1,t=1;if(r==null||r==-1)r=m.length;for(var u=0;u<r;u++){if(m.charAt(u)=="(")t+=1;else if(m.charAt(u)==")")t-=1;if(t==0){m=u;break a}}m=-1}if(m==-1)return"Template syntax error: unmatched '%(' in chunk starting at: "+l[q].substring(0,15);key=l[q].substring(0,m);rest=l[q].substring(m);match=c.exec(rest);if(match==null)return"Template syntax error: invalid type specifier starting at '"+rest+
"'";rest=match[4];n.push(key);n.push(match[1]|0);n.push(match[2]|0);n.push(match[3]);n.push(rest)}return n}function g(l){var n=$(l.split(h)).map(function(){var m=null;return $(this.split(/\s"/)).zip("split").call(/"\s*/).flatten().fold(function(q,v){return $(q.split(j)).map(function(){var r=this.valueOf(),t=r.match(f),u=r.match(a),x=r.match(b);r=r.match(e);var w=null;if(t==null||t.length>1)throw Error("Invalid synth expression: "+l);t=t[0];if(t==="+"&&m!=null)return m=m.parentNode;w=document.createElement(t);
if(u!=null)w.id=u[0].replace(o,"");if(x!=null)w.className=$(x).zip("replace").call(p,"").join(" ");$(r).zip("replace").call(k,"").zip("replace").call(s,"").zip("split").call("=").flatten().fold(function(A,B){w.setAttribute(A,B)});m!=null&&m.appendChild(w);return m=w}).push(v)}).flatten()}).flatten();n.reduce(function(m,q){if(isString(q)){m.appendChild(document.createTextNode(q));return m}else return q==null?m:q});return n.take(1)}var c=/([0-9#0+-]*)\.*([0-9#+-]*)([diouxXeEfFgGcrsqm])(.*)/;d.cache=
{};var f=/^\s*([A-Za-z0-9+]+)/g,a=/#([^\[.# "']+)/g,b=/\.([^\[.# "']+)/g,e=/\[([^\[.# "'=\]]+)=*([^\]]*)\]/g,h=/,\s*/,j=/ /,k=/(?:^\[)|(?:\]$)/g,p=/\./,o=/#/,s=/(?:^["'])|(?:["']$)/g;Bling.synth=g;return{template:function(l){l=Object.Extend({},l);this.render=function(n){var m=this.map(Bling.HTML.stringify).join("");n=Object.Extend(l,n);m=d.cache[m]||(d.cache[m]=d(m));for(var q=[m[0]],v=1,r=1,t=m.length;r<t-4;r+=5){var u=m[r],x=m[r+1],w=m[r+2],A=m[r+3],B=m[r+4],z=n[u];if(z==null)z="missing required value: "+
u;switch(A){case "d":q[v++]=""+parseInt(z);break;case "f":q[v++]=parseFloat(z).toFixed(w);break;default:q[v++]=""+z}if(x>0)q[v]=String.PadLeft(q[v],x);q[v++]=B}return q.join("")};return this.remove()},render:function l(n){return l(this.map(Bling.HTML.stringify).join(""),n)},synth:function(l){return g(l).appendTo(this)}}});
>>>>>>> 7f84d5aded8633dbcff1bb59065f1a9c236c80ac
