(function(f){return f.plugin(function(){var i,e,d,a;e={};d=function(a,b){return e[a]=b};i=function(){return e[obj.t]};a=[];Object.Type.extend(null,{compact:function(a){return Object.String(a)}});Object.Type.extend("undefined",{compact:function(){return""}});Object.Type.extend("null",{compact:function(){return""}});Object.Type.extend("string",{compact:Function.Identity});Object.Type.extend("array",{compact:function(a){var b,g,h,j;j=[];g=0;for(h=a.length;g<h;g++)b=a[g],j.push(Object.Compact(b));return j.join("")}});
Object.Type.extend("bling",{compact:function(a){return a.map(Object.Compact).join("")}});Object.Type.extend("object",{compact:function(a){var b;return Object.Compact(null!=(b=i(a))?b.call(a,a):void 0)}});Object.Compact=function(c){var b;a.push(c);null!=(b=Object.Type.lookup(c))&&b.compact(c);return a.pop()};Object.Extend(Object.Compact,{register:d,lookup:i});d("page",function(){return["<!DOCTYPE html><html><head>",this.head,"</head><body>",this.body,"</body></html>"]});d("text",function(){return this.EN});
d("link",function(){var a,b,g,h,j;a=f(["<a"]);j=["href","name","target"];g=0;for(h=j.length;g<h;g++)b=j[g],b in this&&a.extend(" ",b,"='",this[b],"'");return a.extend(">",node.content,"</a>")});f.assert("<!DOCTYPE html><html><head></head><body>Hello World</body></html>"===Object.Compact({t:"page",head:[],body:{type:"text",EN:"Hello World"}}));return{name:"Compact"}})})(Bling);
(function(f){return f.plugin(function(){var i,e;i=function(d,a){return Object.Extend(document.createElement(d),a)};e=function(d,a){var c,b,g;c=g=null;b=i(d,Object.Extend(a,{"onload!":function(){if(null!=g)return f.publish(g)}}));f("head").delay(10,function(){var a=this;return null!=c?f.subscribe(c,function(){return a.append(b)}):this.append(b)});b=f(b);return Object.Extend(b,{depends:function(a){c=d+"-"+a;return b},provides:function(a){g=d+"-"+a;return b}})};return{name:"LazyLoader",$:{script:function(d){return e("script",
{"src!":d})},style:function(d){return e("link",{"href!":d,"rel!":"stylesheet"})}}}})})(Bling);
(function(f){return f.plugin(function(){var i,e,d,a;e={};d=function(a,b){return e[a]=b};i=function(){return e[obj.t]};a=[];Object.Type.extend(null,{compact:function(a){return Object.String(a)}});Object.Type.extend("undefined",{compact:function(){return""}});Object.Type.extend("null",{compact:function(){return""}});Object.Type.extend("string",{compact:Function.Identity});Object.Type.extend("array",{compact:function(a){var b,g,h,j;j=[];g=0;for(h=a.length;g<h;g++)b=a[g],j.push(Object.Compact(b));return j.join("")}});
Object.Type.extend("bling",{compact:function(a){return a.map(Object.Compact).join("")}});Object.Type.extend("object",{compact:function(a){var b;return Object.Compact(null!=(b=i(a))?b.call(a,a):void 0)}});Object.Compact=function(c){var b;a.push(c);null!=(b=Object.Type.lookup(c))&&b.compact(c);return a.pop()};Object.Extend(Object.Compact,{register:d,lookup:i});d("page",function(){return["<!DOCTYPE html><html><head>",this.head,"</head><body>",this.body,"</body></html>"]});d("text",function(){return this.EN});
d("link",function(){var a,b,g,h,j;a=f(["<a"]);j=["href","name","target"];g=0;for(h=j.length;g<h;g++)b=j[g],b in this&&a.extend(" ",b,"='",this[b],"'");return a.extend(">",node.content,"</a>")});f.assert("<!DOCTYPE html><html><head></head><body>Hello World</body></html>"===Object.Compact({t:"page",head:[],body:{type:"text",EN:"Hello World"}}));return{name:"Compact"}})})(Bling);
(function(f){return f.plugin(function(){var i,e;i=function(d,a){return Object.Extend(document.createElement(d),a)};e=function(d,a){var c,b,g;c=g=null;b=i(d,Object.Extend(a,{"onload!":function(){if(null!=g)return f.publish(g)}}));f("head").delay(10,function(){var a=this;return null!=c?f.subscribe(c,function(){return a.append(b)}):this.append(b)});b=f(b);return Object.Extend(b,{depends:function(a){c=d+"-"+a;return b},provides:function(a){g=d+"-"+a;return b}})};return{name:"LazyLoader",$:{script:function(d){return e("script",
{"src!":d})},style:function(d){return e("link",{"href!":d,"rel!":"stylesheet"})}}}})})(Bling);
(function(f){return f.plugin(function(){var i,e,d,a,c,b,g,h,j,l,s,m,k,n,o,r;s=/!==|!=|!|\#|\%|\%=|\&|\&\&|\&\&=|&=|\*|\*=|\+|\+=|-|-=|->|\.{1,3}|\/|\/=|:|::|;|<<=|<<|<=|<|===|==|=|>>>=|>>=|>=|>>>|>>|>|\?|@|\[|\]|}|{|\^|\^=|\^\^|\^\^=|\|=|\|\|=|\|\||\||~/g;j=/\b[Ff]unction\b|\bvar\b|\.prototype\b|\.__proto__\b|\bString\b|\bArray\b|\bNumber\b|\bObject\b|\bbreak\b|\bcase\b|\bcontinue\b|\bdelete\b|\bdo\b|\bif\b|\belse\b|\bfinally\b|\binstanceof\b|\breturn\b|\bthrow\b|\btry\b|\btypeof\b|\btrue\b|\bfalse\b/g;i=
/\d+\.*\d*/g;e=/\$(\(|\.)/g;r=/\t/g;k=/\/\/.*?(?:\n|$)/;l=/\/\*(?:.|\n)*?\*\//;a=function(a){return a?"<span class='com'>"+a+"</span>":""};m=function(a){return a?"<span class='str'>"+a+"</span>":""};b=function(a,c){var h,b;h=a.indexOf('"',c);b=a.indexOf("'",c);-1===h&&(h=a.length);-1===b&&(b=a.length);return h===b?[null,-1]:h<b?['"',h]:["'",b]};d=function(a,c,h){for(c=a.indexOf(h,c);"\\"===a.charAt(c-1)&&0<c&&c<a.length;)c=a.indexOf(h,c+1);return c};o=function(a){var c,h,g,j,k;c=0;g=a.length;k=[];
if(!Object.IsString(a))if(Object.IsFunction(a.toString))a=a.toString(),g=a.length;else throw TypeError("invalid string argument to split_quoted");for(;c<g;){j=b(a,c);h=j[1];if(-1===h){k.push(a.substring(c));break}k.push(a.substring(c,h));c=d(a,h+1,j[0]);if(-1===c)throw Error("unclosed quote: "+j[0]+" starting at "+h);k.push(a.substring(h,c+1));c+=1}return k};c=function(a){var c;c=a.match(k);a=a.match(l);return c===a?[-1,null]:null===c&&null!==a?[a.index,a[0]]:null!==c&&null===a?[c.index,c[0]]:a.index<
c.index?[a.index,a[0]]:[c.index,c[0]]};n=function(a){var h,b,g,j,k,l;k=[];h=0;for(g=a.length;h<g;)if(l=a.substring(h),j=c(l),b=j[0],-1<b)k.push(l.substring(0,b)),k.push(j[1]),h+=b+j[1].length;else{k.push(l);break}return k};g=function(a,c){return a.replace(s,"<span class='opr'>$&</span>").replace(i,"<span class='num'>$&</span>").replace(j,"<span class='kwd'>$&</span>").replace(e,"<span class='bln'>$$</span>$1").replace(r,"&nbsp;&nbsp;")+m(c)};h=function(c,h){return f(o(c)).fold(g).join("")+a(h)};return{name:"PrettyPrint",
$:{prettyPrint:function(a,c){var b,j;Object.IsFunction(a)&&(a=a.toString());if(!Object.IsString(a))throw TypeError("prettyPrint requires a function or string to format, not '"+Object.Type(a)+"'");if(0===f("style#prettyPrint").length){j="code.pp .bln { font-size: 17px; } ";c=Object.Extend({opr:"#880",str:"#008",com:"#080",kwd:"#088",num:"#808",bln:"#800"},c);for(b in c)j+="code.pp ."+b+" { color: "+c[b]+"; } ";f.synth("style#prettyPrint").text(j).appendTo("head")}return"<code class='pp'>"+f(n(a)).fold(h).join("")+
"</code>"}}}})})(Bling);
(function(){var f=Object.prototype.hasOwnProperty,i=function(e,d){function a(){this.constructor=e}for(var c in d)f.call(d,c)&&(e[c]=d[c]);a.prototype=d.prototype;e.prototype=new a;e.__super__=d.prototype;return e};(function(e){e.plugin(function(){return{name:"StateMachine",$:{StateMachine:function(){function d(a){this.reset();this.table=a;Object.defineProperty(this,"modeline",{get:this.table[this._mode]});Object.defineProperty(this,"mode",{set:function(a){var b;this._lastMode=this._mode;this._mode=
a;if(this._mode!==this._lastMode&&null!=this.modeline&&"enter"in this.modeline)for(b=this.modeline.enter.call(this);Object.IsFunction(b);)b=b.call(this);return a},get:function(){return this._mode}})}d.prototype.reset=function(){return this._lastMode=this._mode=null};d.prototype.GO=function(a){return function(){return this.mode=a}};d.GO=function(a){return function(){return this.mode=a}};d.prototype.run=function(a){var c,b,g,h,j,l;h=this.mode=0;for(j=a.length;h<j;h++){c=a[h];g=this.modeline;null==g?
b=null:c in g?b=g[c]:"def"in g&&(b=g.def);for(;Object.IsFunction(b);)b=b.call(this,c)}if(Object.IsFunction(null!=(l=this.modeline)?l.eof:void 0))b=this.modeline.eof.call(this);for(;Object.IsFunction(b);)b=b.call(this);this.reset();return this};return d}()}}});return e.plugin(function(){var d;d=function(){function a(){a.__super__.constructor.call(this,a.STATE_TABLE);this.fragment=this.parent=document.createDocumentFragment()}i(a,e.StateMachine);a.STATE_TABLE=[{enter:function(){this.tag=this.id=this.cls=
this.attr=this.val=this.text="";this.attrs={};return this.GO(1)}},{'"':a.GO(6),"'":a.GO(7),"#":a.GO(2),".":a.GO(3),"[":a.GO(4)," ":a.GO(9),"+":a.GO(11),",":a.GO(10),def:function(a){return this.tag+=a},eof:a.GO(13)},{".":a.GO(3),"[":a.GO(4)," ":a.GO(9),"+":a.GO(11),",":a.GO(10),def:function(a){return this.id+=a},eof:a.GO(13)},{enter:function(){if(0<this.cls.length)return this.cls+=" "},"#":a.GO(2),".":a.GO(3),"[":a.GO(4)," ":a.GO(9),"+":a.GO(11),",":a.GO(10),def:function(a){return this.cls+=a},eof:a.GO(13)},
{"=":a.GO(5),"]":function(){this.attrs[this.attr]=this.val;return this.GO(1)},def:function(a){return this.attr+=a},eof:a.GO(12)},{"]":function(){this.attrs[this.attr]=this.val;return this.GO(1)},def:function(a){return this.val+=a},eof:a.GO(12)},{'"':a.GO(8),def:function(a){return this.text+=a},eof:a.GO(12)},{"'":a.GO(8),def:function(a){return this.text+=a},eof:a.GO(12)},{enter:function(){this.emitText();return this.GO(0)}},{enter:function(){this.emitNode();return this.GO(0)}},{enter:function(){this.emitNode();
this.parent=null;return this.GO(0)}},{enter:function(){var a;this.emitNode();this.parent=null!=(a=this.parent)?a.parentNode:void 0;return this.GO(0)}},{enter:function(){return e.log("Error in synth expression: "+this.input)}},{enter:function(){this.tag.length&&this.emitNode();if(this.text.length)return this.emitText()}}];a.prototype.emitNode=function(){var a,b;b=document.createElement(this.tag);b.id=this.id||null;b.className=this.cls||null;for(a in this.attrs)b.setAttribute(a,this.attrs[a]);this.parent.appendChild(b);
return this.parent=b};a.prototype.emitText=function(){this.parent.appendChild(e.HTML.parse(this.text));return this.text=""};return a}();return{name:"Synth",$:{synth:function(a){var c;c=new d;c.run(a);return 1===c.fragment.childNodes.length?e(c.fragment.childNodes[0]):e(c.fragment)}}}})})(Bling)}).call(this);
(function(){var f=Object.prototype.hasOwnProperty,i=function(e,d){function a(){this.constructor=e}for(var c in d)f.call(d,c)&&(e[c]=d[c]);a.prototype=d.prototype;e.prototype=new a;e.__super__=d.prototype;return e};(function(e){var d,a;d={};e.plugin(function(){var a,b;a=null;d={};b={register_engine:function(b,h){d[b]=h;if(null==a)return a=b},render:function(b,h){if(a in d)return d[a](b,h)}};b.__defineSetter__("engine",function(b){if(!b in d)throw Error("invalid template engine: "+b+" not one of "+
Object.Keys(d));return a=b});b.__defineGetter__("engine",function(){return a});return{name:"Template",$:{template:b}}});e.template.register_engine("null",function(){return function(a){return a}}());a=function(a,b,g,h,j){var l,d,e;null==j&&(j=-1);l=1;0>j&&(j=a.length+1+j);for(d=h;h<=j?d<j:d>j;h<=j?d++:d--)if(e=a[d],e===g?l+=1:e===b&&(l-=1),0===l)return d;return-1};e.template.register_engine("pythonic",function(){var c,b,g;g=/([0-9#0+-]*)\.*([0-9#+-]*)([diouxXeEfFgGcrsqm])((?:.|\n)*)/;c=/%[\(\/]/;b=
function(h){var b,l,d,e,k,n,f,h=h.split(c);k=h.length;f=[h[0]];for(l=d=1;1<=k?l<k:l>k;1<=k?l++:l--){b=a(h[l],")","(",0,-1);if(-1===b)return"Template syntax error: unmatched '%(' starting at: "+h[l].substring(0,15);e=h[l].substring(0,b);n=h[l].substring(b);b=g.exec(n);if(null===b)return"Template syntax error: invalid type specifier starting at '"+n+"'";n=b[4];f[d++]=e;f[d++]=b[1]|0;f[d++]=b[2]|0;f[d++]=b[3];f[d++]=n}return f};b.cache={};return function(a,c){var g,d,e,k,n,f,i,p,t,q,u;g=b.cache[a];null==
g&&(g=b.cache[a]=b(a));f=[g[0]];k=1;d=g.length;e=1;for(u=d-5;e<=u;e+=5){p=g.slice(e,e+4+1||9E9);n=p[0];i=p[1];d=p[2];t=p[3];p=p[4];q=c[n];null==q&&(q="missing value: "+n);switch(t){case "d":f[k++]=""+parseInt(q,10);break;case "f":f[k++]=parseFloat(q).toFixed(d);break;case "s":f[k++]=""+q;break;default:f[k++]=""+q}0<i&&(f[k]=String.PadLeft(f[k],i));f[k++]=p}return f.join("")}}());return e.template.register_engine("js-eval",function(){(function(){function a(){a.__super__.constructor.apply(this,arguments)}
i(a,e.StateMachine);a.STATE_TABLE=[{enter:function(){this.data=[];return this.GO(1)}},{}];return a})();return function(a){return a}}())})(Bling)}).call(this);
(function(f){return f.plugin(function(){var i,e,d;d=function(a){var c,b,g,h;c=a.indexOf(":");if(0<c)return g=parseInt(a.slice(0,c),10),b=a.slice(c+1,c+1+g),h=a[c+1+g],a=a.slice(c+g+2),b=function(){switch(h){case "#":return Number(b);case "'":return""+b;case "!":return"true"===b;case "~":return null;case "]":return i(b);case "}":return e(b)}}(),[b,a]};i=function(a){var c,b;for(c=[];0<a.length;)a=d(a),b=a[0],a=a[1],c.push(b);return c};e=function(a){var c,b,g;for(c={};0<a.length;)g=d(a),b=g[0],a=g[1],
a=d(a),g=a[0],a=a[1],c[b]=g;return c};return{name:"TNET",$:{TNET:{stringify:function(a){var c,b,g;g=function(){switch(Object.Type(a)){case "number":return[""+a,"#"];case "string":return[a,"'"];case "function":return[""+a,"'"];case "boolean":return[""+!!a,"!"];case "null":return["","~"];case "undefined":return["","~"];case "array":return[function(){var c,g,d;d=[];c=0;for(g=a.length;c<g;c++)b=a[c],d.push(f.TNET.stringify(b));return d}().join(""),"]"];case "object":return[function(){var c;c=[];for(b in a)c.push(f.TNET.stringify(b)+
f.TNET.stringify(a[b]));return c}().join(""),"}"]}}();c=g[0];return(c.length|0)+":"+c+g[1]},parse:function(a){var c;return null!=(c=d(a))?c[0]:void 0}}}}})})(Bling);
(function(f){return f.plugin(function(){var i,e,d,a,c,b;e=function(a,c){var b,c=Object.Extend({autoOpen:!1,draggable:!0},c);b=f(a).addClass("dialog");c.draggable&&b.draggable();c.autoOpen&&b.show().center();b.find("button.close, .close-button").bind("click touchstart",function(){b.hide();return!1});return b};d=function(a,c){var b,d,e,m,k,c=Object.Extend({handleCSS:{}},c);c.handleCSS=Object.Extend({position:"absolute",top:"0px",left:"0px",width:"100%",height:"6px"},c.handleCSS);b=f(a);e=!1;m=k=0;d=
f.synth("div.handle").defaultCss({background:"-webkit-gradient(linear, 50% 0%, 50% 100%, from(#eee), color-stop(0.25, #bbb), color-stop(0.3, #eee), color-stop(0.5, #eee), to(#bbb))",height:"6px","border-radius":"3px",cursor:"move"}.css(c.handleCSS.bind("mousedown, touchstart",function(a){e=!0;m||(m=a.pageX);k||(k=a.pageY);return!1})));f(document.bind("mousemove, touchmove",function(a){var c;if(e)return c=a.pageX-m,a=a.pageY-k,b.transform({translate:[c,a]},0).trigger("drag",{dragObject:b}),!1})).bind("mouseup, touchend",
function(){var a;if(e)return e=!1,a=d.position()[0],f(document.elementFromPoint(a.left,a.top-1).trigger("drop",{dropObject:b}))});return b.addClass("draggable").css({position:"relative","padding-top":b.css("padding-top").map(Number.AtLeast(parseInt(c.handleCSS.height,10))).px().first()}.append(d))};a=function(a,c){var b,d,e,m,c=Object.Extend({change:Function.Empty,backgroundColor:"#fff",barColor:"rgba(0,128,0,0.5)",textColor:"white",reset:!1},c);b=f(a).addClass("progress-bar");m=0;c.reset&&(d=b.css("background").first(),
e=b.css("color").first());return b.zap("updateProgress",function(a){for(;1<a;)a/=100;m=a;1===a&&c.reset?b.css("background",d).css("color",e):b.css({background:"-webkit-gradient(linear, 0 0, "+parseInt(100*a)+"% 0, color-stop(0, "+c.barColor+"), color-stop(0.98, "+c.barColor+"), color-stop(1.0, "+c.backgroundColor+"))",color:c.textColor});if(Object.IsFunc(c.change))return c.change(m)})};i=function(a,c){var b,d,c=Object.Extend({exclusive:!1,sticky:!1},c);d=f(a).addClass("accordion");b=function(a){var b,
g,j,a=f(a).children().first().filter("*");if(2!==a.len())throw Exception("accordion row requires 2 elements, not "+a.len());j=a.eq(0).addClass("title");b=a.eq(1).addClass("body").hide();g=!1;return j.click(function(){c.exclusive&&d.find(".body").hide();if(g){if(c.sticky)return b.show().addClass("visible"),j.addClass("selected").trigger("select"),g=!0;b.hide().removeClass("visible");j.removeClass("selected").trigger("deselect");return g=!1}b.show().addClass("visible");j.addClass("selected").trigger("select");
return g=!0})};d.bind("DOMNodeInserted",function(a){var c;c=d.children().first().filter("*");a=f(a.target).parents().first();return b(a.intersect(c))});d.children().first().filter("*").map(b);return d};b=function(a){var c,b,d;b=f(a).css({position:"relative",top:"0px",left:"0px"}.hide().map(f));c=0;b[c].show();b.next=function(){b[c].hide();c=++c%nn;return b[c].show()};b.activate=function(a){b[c].hide();c=a;return b[a].show()};a=0;for(d=b.len();0<=d?a<d:a>d;0<=d?a++:a--)b[a].zap("_viewIndex",a.zap("activate",
function(){return b.activate(this._viewIndex)}));return b};c=function(a,c){var b,d,e;e=f(a);c=f(c).viewStack();d=e.len();for(b=0;0<=d?b<=d:b>=d;0<=d?b++:b--)e._tabIndex=b;f(e[0]).addClass("active");return e.click(function(){e.removeClass("active");c.activate(this._tabIndex);return f(this).addClass("active")})};return{name:"UI",$:{UI:{Draggable:d,ProgressBar:a,ViewStack:b,Tabs:c,Accordion:i}},dialog:function(a){return e(this,a)},progressBar:function(c){return a(this,c)},viewStack:function(a){return b(this,
a)},tabs:function(a){return c(this,a)},accordion:function(a){return i(this,a)},draggable:function(a){return d(this,a)}}})})(Bling);
(function(){var f=Array.prototype.slice;$.plugin(function(){var i,e,d,a,c,b,g,h,j,l,s,m;h="px,pt,pc,em,%,in,cm,mm,ex".split(",");i=/(\d+\.*\d*)(px|pt|pc|em|%|in|cm|mm|ex)/;b=function(a){return i.exec(a)[2](i.test(a)?void 0:"")};a=function(c,b){return a[c][b]()};g=function(a){return function(){return a}};j=0;for(s=h.length;j<s;j++){e=h[j];l=0;for(m=h.length;l<m;l++)d=h[l],(a[e]||(a[e]={}))[d]=g(+(e===d||""===e||""===d))}a["in"].pt=function(){return 72};a["in"].px=function(){return 96};a["in"].cm=function(){return 2.54};
a.pc.pt=function(){return 12};a.cm.mm=function(){return 10};a.em.px=function(){var a,c;c=$("<span style='font-size:1em;visibility:hidden'>x</span>").appendTo("body");a=c.width().first();c.remove();return a};a.ex.px=function(){var a,c;c=$("<span style='font-size:1ex;visibility:hidden'>x</span>").appendTo("body");a=c.width().first();c.remove();return a};a.ex.em=function(){return 2};e=function(){var c,b,d,j,e,l;l=[];j=0;for(e=h.length;j<e;j++)c=h[j],l.push(function(){var j,e,l;l=[];j=0;for(e=h.length;j<
e;j++)b=h[j],!a(c,b)&&a(b,c)&&(console.log("found inverse: "+c+"."+b),a[c][b]=g(1/a(b,c))),l.push(function(){var j,e,l;l=[];e=0;for(j=h.length;e<j;e++)d=h[e],!a(c,d)&&a(c,b)&&a(b,d)?(console.log("found induction: "+c+"."+d),l.push(a[c][d]=g(a(c,b)*a(b,d)))):l.push(void 0);return l}());return l}());return l};e();e();$.assert("10cm"===parseFloat("300px")*a[b("300px")].cm()+"cm");c=function(a,c){var b,h,g;g=[];b=0;for(h=c.length;0<=h?b<h:b>h;0<=h?b++:b--)g.push(c[b]=convertTo(a,c[b]));return g};Object.Type.register("units",
{match:function(a){return i.test(a)}});e=function(a){return function(){var h,g;h=1<=arguments.length?f.call(arguments,0):[];c(g=b(this[0]),this);return a.apply(this,h)+g}};return{min:e(function(){return this.reduce(function(a){return Math.min(parseFloat(this),a)})}),max:e(function(){return this.reduce(function(a){return Math.max(parseFloat(this),a)})}),sum:e(function(){return this.reduce(function(a){return parseFloat(this)+a})}),mean:e(function(){return parseFloat(this.sum())/this.length}),magnitude:e(function(){return Math.sqrt(this.floats().squares().sum())}),
squares:function(){return this.map(function(){var a;return(a=parseFloat(this))*a})},scale:function(a){return this.map(function(){return a*parseFloat(this)})},add:function(a){return this.map(function(){return a+this})},normalize:function(){return this.scale(1/this.magnitude())}}})}).call(this);
$.plugin(function(){var f,i,e,d;f=function(){return"EOF"};for(d=0;1E3>d;d++)i=d;e=0;return function(a){a=extend({item:function(){return f},action:Function.Identity,latency:10},a);return extend(new $.EventEmitter,{run:function(){var c,b=this;c=function(){var g;if((g=a.action(a.item()))!==f)return b.emit("data",g),setTimeout(c,a.latency)};return setTimeout(c,a.latency)}})}({item:function(){return i[e++](e<i.length?void 0:f)},action:function(a){return a*a-1},latency:10}).on("data",function(a){return console.log("data:",
a.on("error",function(a){return console.log("error:",a.run())}))})});
(function(f){return f.plugin(function(){var i,e,d,a;e={};d=function(a,b){return e[a]=b};i=function(){return e[obj.t]};a=[];Object.Type.extend(null,{compact:function(a){return Object.String(a)}});Object.Type.extend("undefined",{compact:function(){return""}});Object.Type.extend("null",{compact:function(){return""}});Object.Type.extend("string",{compact:Function.Identity});Object.Type.extend("array",{compact:function(a){var b,g,h,d;d=[];g=0;for(h=a.length;g<h;g++)b=a[g],d.push(Object.Compact(b));return d.join("")}});
Object.Type.extend("bling",{compact:function(a){return a.map(Object.Compact).join("")}});Object.Type.extend("object",{compact:function(a){var b;return Object.Compact(null!=(b=i(a))?b.call(a,a):void 0)}});Object.Compact=function(c){var b;a.push(c);null!=(b=Object.Type.lookup(c))&&b.compact(c);return a.pop()};Object.Extend(Object.Compact,{register:d,lookup:i});d("page",function(){return["<!DOCTYPE html><html><head>",this.head,"</head><body>",this.body,"</body></html>"]});d("text",function(){return this.EN});
d("link",function(){var a,b,g,h,d;a=f(["<a"]);d=["href","name","target"];g=0;for(h=d.length;g<h;g++)b=d[g],b in this&&a.extend(" ",b,"='",this[b],"'");return a.extend(">",node.content,"</a>")});f.assert("<!DOCTYPE html><html><head></head><body>Hello World</body></html>"===Object.Compact({t:"page",head:[],body:{type:"text",EN:"Hello World"}}));return{name:"Compact"}})})(Bling);
(function(f){return f.plugin(function(){var i,e,d,a,c,b,g,h,j,l,s,m,k,n,o,r;s=/!==|!=|!|\#|\%|\%=|\&|\&\&|\&\&=|&=|\*|\*=|\+|\+=|-|-=|->|\.{1,3}|\/|\/=|:|::|;|<<=|<<|<=|<|===|==|=|>>>=|>>=|>=|>>>|>>|>|\?|@|\[|\]|}|{|\^|\^=|\^\^|\^\^=|\|=|\|\|=|\|\||\||~/g;j=/\b[Ff]unction\b|\bvar\b|\.prototype\b|\.__proto__\b|\bString\b|\bArray\b|\bNumber\b|\bObject\b|\bbreak\b|\bcase\b|\bcontinue\b|\bdelete\b|\bdo\b|\bif\b|\belse\b|\bfinally\b|\binstanceof\b|\breturn\b|\bthrow\b|\btry\b|\btypeof\b|\btrue\b|\bfalse\b/g;
i=/\d+\.*\d*/g;e=/\$(\(|\.)/g;r=/\t/g;k=/\/\/.*?(?:\n|$)/;l=/\/\*(?:.|\n)*?\*\//;a=function(a){return a?"<span class='com'>"+a+"</span>":""};m=function(a){return a?"<span class='str'>"+a+"</span>":""};b=function(a,c){var b,h;b=a.indexOf('"',c);h=a.indexOf("'",c);-1===b&&(b=a.length);-1===h&&(h=a.length);return b===h?[null,-1]:b<h?['"',b]:["'",h]};d=function(a,c,b){for(c=a.indexOf(b,c);"\\"===a.charAt(c-1)&&0<c&&c<a.length;)c=a.indexOf(b,c+1);return c};o=function(a){var c,h,g,j,e;c=0;g=a.length;e=
[];if(!Object.IsString(a))if(Object.IsFunction(a.toString))a=a.toString(),g=a.length;else throw TypeError("invalid string argument to split_quoted");for(;c<g;){j=b(a,c);h=j[1];if(-1===h){e.push(a.substring(c));break}e.push(a.substring(c,h));c=d(a,h+1,j[0]);if(-1===c)throw Error("unclosed quote: "+j[0]+" starting at "+h);e.push(a.substring(h,c+1));c+=1}return e};c=function(a){var c;c=a.match(k);a=a.match(l);return c===a?[-1,null]:null===c&&null!==a?[a.index,a[0]]:null!==c&&null===a?[c.index,c[0]]:
a.index<c.index?[a.index,a[0]]:[c.index,c[0]]};n=function(a){var b,h,g,d,j,e;j=[];b=0;for(g=a.length;b<g;)if(e=a.substring(b),d=c(e),h=d[0],-1<h)j.push(e.substring(0,h)),j.push(d[1]),b+=h+d[1].length;else{j.push(e);break}return j};g=function(a,c){return a.replace(s,"<span class='opr'>$&</span>").replace(i,"<span class='num'>$&</span>").replace(j,"<span class='kwd'>$&</span>").replace(e,"<span class='bln'>$$</span>$1").replace(r,"&nbsp;&nbsp;")+m(c)};h=function(c,b){return f(o(c)).fold(g).join("")+
a(b)};return{name:"PrettyPrint",$:{prettyPrint:function(a,c){var b,g;Object.IsFunction(a)&&(a=a.toString());if(!Object.IsString(a))throw TypeError("prettyPrint requires a function or string to format, not '"+Object.Type(a)+"'");if(0===f("style#prettyPrint").length){g="code.pp .bln { font-size: 17px; } ";c=Object.Extend({opr:"#880",str:"#008",com:"#080",kwd:"#088",num:"#808",bln:"#800"},c);for(b in c)g+="code.pp ."+b+" { color: "+c[b]+"; } ";f.synth("style#prettyPrint").text(g).appendTo("head")}return"<code class='pp'>"+
f(n(a)).fold(h).join("")+"</code>"}}}})})(Bling);
(function(){var f=Object.prototype.hasOwnProperty,i=function(e,d){function a(){this.constructor=e}for(var c in d)f.call(d,c)&&(e[c]=d[c]);a.prototype=d.prototype;e.prototype=new a;e.__super__=d.prototype;return e};(function(e){e.plugin(function(){return{name:"StateMachine",$:{StateMachine:function(){function d(a){this.reset();this.table=a;Object.defineProperty(this,"modeline",{get:this.table[this._mode]});Object.defineProperty(this,"mode",{set:function(a){var b;this._lastMode=this._mode;this._mode=
a;if(this._mode!==this._lastMode&&null!=this.modeline&&"enter"in this.modeline)for(b=this.modeline.enter.call(this);Object.IsFunction(b);)b=b.call(this);return a},get:function(){return this._mode}})}d.prototype.reset=function(){return this._lastMode=this._mode=null};d.prototype.GO=function(a){return function(){return this.mode=a}};d.GO=function(a){return function(){return this.mode=a}};d.prototype.run=function(a){var c,b,g,h,d,e;h=this.mode=0;for(d=a.length;h<d;h++){c=a[h];g=this.modeline;null==g?
b=null:c in g?b=g[c]:"def"in g&&(b=g.def);for(;Object.IsFunction(b);)b=b.call(this,c)}if(Object.IsFunction(null!=(e=this.modeline)?e.eof:void 0))b=this.modeline.eof.call(this);for(;Object.IsFunction(b);)b=b.call(this);this.reset();return this};return d}()}}});return e.plugin(function(){var d;d=function(){function a(){a.__super__.constructor.call(this,a.STATE_TABLE);this.fragment=this.parent=document.createDocumentFragment()}i(a,e.StateMachine);a.STATE_TABLE=[{enter:function(){this.tag=this.id=this.cls=
this.attr=this.val=this.text="";this.attrs={};return this.GO(1)}},{'"':a.GO(6),"'":a.GO(7),"#":a.GO(2),".":a.GO(3),"[":a.GO(4)," ":a.GO(9),"+":a.GO(11),",":a.GO(10),def:function(a){return this.tag+=a},eof:a.GO(13)},{".":a.GO(3),"[":a.GO(4)," ":a.GO(9),"+":a.GO(11),",":a.GO(10),def:function(a){return this.id+=a},eof:a.GO(13)},{enter:function(){if(0<this.cls.length)return this.cls+=" "},"#":a.GO(2),".":a.GO(3),"[":a.GO(4)," ":a.GO(9),"+":a.GO(11),",":a.GO(10),def:function(a){return this.cls+=a},eof:a.GO(13)},
{"=":a.GO(5),"]":function(){this.attrs[this.attr]=this.val;return this.GO(1)},def:function(a){return this.attr+=a},eof:a.GO(12)},{"]":function(){this.attrs[this.attr]=this.val;return this.GO(1)},def:function(a){return this.val+=a},eof:a.GO(12)},{'"':a.GO(8),def:function(a){return this.text+=a},eof:a.GO(12)},{"'":a.GO(8),def:function(a){return this.text+=a},eof:a.GO(12)},{enter:function(){this.emitText();return this.GO(0)}},{enter:function(){this.emitNode();return this.GO(0)}},{enter:function(){this.emitNode();
this.parent=null;return this.GO(0)}},{enter:function(){var a;this.emitNode();this.parent=null!=(a=this.parent)?a.parentNode:void 0;return this.GO(0)}},{enter:function(){return e.log("Error in synth expression: "+this.input)}},{enter:function(){this.tag.length&&this.emitNode();if(this.text.length)return this.emitText()}}];a.prototype.emitNode=function(){var a,b;b=document.createElement(this.tag);b.id=this.id||null;b.className=this.cls||null;for(a in this.attrs)b.setAttribute(a,this.attrs[a]);this.parent.appendChild(b);
return this.parent=b};a.prototype.emitText=function(){this.parent.appendChild(e.HTML.parse(this.text));return this.text=""};return a}();return{name:"Synth",$:{synth:function(a){var c;c=new d;c.run(a);return 1===c.fragment.childNodes.length?e(c.fragment.childNodes[0]):e(c.fragment)}}}})})(Bling)}).call(this);
(function(){var f=Object.prototype.hasOwnProperty,i=function(e,d){function a(){this.constructor=e}for(var c in d)f.call(d,c)&&(e[c]=d[c]);a.prototype=d.prototype;e.prototype=new a;e.__super__=d.prototype;return e};(function(e){var d,a;d={};e.plugin(function(){var a,b;a=null;d={};b={register_engine:function(b,h){d[b]=h;if(null==a)return a=b},render:function(b,h){if(a in d)return d[a](b,h)}};b.__defineSetter__("engine",function(b){if(!b in d)throw Error("invalid template engine: "+b+" not one of "+
Object.Keys(d));return a=b});b.__defineGetter__("engine",function(){return a});return{name:"Template",$:{template:b}}});e.template.register_engine("null",function(){return function(a){return a}}());a=function(a,b,g,h,d){var e,f,m;null==d&&(d=-1);e=1;0>d&&(d=a.length+1+d);for(f=h;h<=d?f<d:f>d;h<=d?f++:f--)if(m=a[f],m===g?e+=1:m===b&&(e-=1),0===e)return f;return-1};e.template.register_engine("pythonic",function(){var c,b,d;d=/([0-9#0+-]*)\.*([0-9#+-]*)([diouxXeEfFgGcrsqm])((?:.|\n)*)/;c=/%[\(\/]/;b=
function(b){var j,e,f,m,k,n,i,b=b.split(c);k=b.length;i=[b[0]];for(e=f=1;1<=k?e<k:e>k;1<=k?e++:e--){j=a(b[e],")","(",0,-1);if(-1===j)return"Template syntax error: unmatched '%(' starting at: "+b[e].substring(0,15);m=b[e].substring(0,j);n=b[e].substring(j);j=d.exec(n);if(null===j)return"Template syntax error: invalid type specifier starting at '"+n+"'";n=j[4];i[f++]=m;i[f++]=j[1]|0;i[f++]=j[2]|0;i[f++]=j[3];i[f++]=n}return i};b.cache={};return function(a,c){var d,g,e,f,n,i,r,p,t,q,u;d=b.cache[a];null==
d&&(d=b.cache[a]=b(a));i=[d[0]];f=1;g=d.length;e=1;for(u=g-5;e<=u;e+=5){p=d.slice(e,e+4+1||9E9);n=p[0];r=p[1];g=p[2];t=p[3];p=p[4];q=c[n];null==q&&(q="missing value: "+n);switch(t){case "d":i[f++]=""+parseInt(q,10);break;case "f":i[f++]=parseFloat(q).toFixed(g);break;case "s":i[f++]=""+q;break;default:i[f++]=""+q}0<r&&(i[f]=String.PadLeft(i[f],r));i[f++]=p}return i.join("")}}());return e.template.register_engine("js-eval",function(){(function(){function a(){a.__super__.constructor.apply(this,arguments)}
i(a,e.StateMachine);a.STATE_TABLE=[{enter:function(){this.data=[];return this.GO(1)}},{}];return a})();return function(a){return a}}())})(Bling)}).call(this);
(function(f){return f.plugin(function(){var i,e,d;d=function(a){var c,b,d,h;c=a.indexOf(":");if(0<c)return d=parseInt(a.slice(0,c),10),b=a.slice(c+1,c+1+d),h=a[c+1+d],a=a.slice(c+d+2),b=function(){switch(h){case "#":return Number(b);case "'":return""+b;case "!":return"true"===b;case "~":return null;case "]":return i(b);case "}":return e(b)}}(),[b,a]};i=function(a){var c,b;for(c=[];0<a.length;)a=d(a),b=a[0],a=a[1],c.push(b);return c};e=function(a){var c,b,g;for(c={};0<a.length;)g=d(a),b=g[0],a=g[1],
a=d(a),g=a[0],a=a[1],c[b]=g;return c};return{name:"TNET",$:{TNET:{stringify:function(a){var c,b,d;d=function(){switch(Object.Type(a)){case "number":return[""+a,"#"];case "string":return[a,"'"];case "function":return[""+a,"'"];case "boolean":return[""+!!a,"!"];case "null":return["","~"];case "undefined":return["","~"];case "array":return[function(){var c,d,g;g=[];c=0;for(d=a.length;c<d;c++)b=a[c],g.push(f.TNET.stringify(b));return g}().join(""),"]"];case "object":return[function(){var c;c=[];for(b in a)c.push(f.TNET.stringify(b)+
f.TNET.stringify(a[b]));return c}().join(""),"}"]}}();c=d[0];return(c.length|0)+":"+c+d[1]},parse:function(a){var c;return null!=(c=d(a))?c[0]:void 0}}}}})})(Bling);
(function(f){return f.plugin(function(){var i,e,d,a,c,b;e=function(a,c){var b,c=Object.Extend({autoOpen:!1,draggable:!0},c);b=f(a).addClass("dialog");c.draggable&&b.draggable();c.autoOpen&&b.show().center();b.find("button.close, .close-button").bind("click touchstart",function(){b.hide();return!1});return b};d=function(a,c){var b,d,e,i,k,c=Object.Extend({handleCSS:{}},c);c.handleCSS=Object.Extend({position:"absolute",top:"0px",left:"0px",width:"100%",height:"6px"},c.handleCSS);b=f(a);e=!1;i=k=0;d=
f.synth("div.handle").defaultCss({background:"-webkit-gradient(linear, 50% 0%, 50% 100%, from(#eee), color-stop(0.25, #bbb), color-stop(0.3, #eee), color-stop(0.5, #eee), to(#bbb))",height:"6px","border-radius":"3px",cursor:"move"}.css(c.handleCSS.bind("mousedown, touchstart",function(a){e=!0;i||(i=a.pageX);k||(k=a.pageY);return!1})));f(document.bind("mousemove, touchmove",function(a){var c;if(e)return c=a.pageX-i,a=a.pageY-k,b.transform({translate:[c,a]},0).trigger("drag",{dragObject:b}),!1})).bind("mouseup, touchend",
function(){var a;if(e)return e=!1,a=d.position()[0],f(document.elementFromPoint(a.left,a.top-1).trigger("drop",{dropObject:b}))});return b.addClass("draggable").css({position:"relative","padding-top":b.css("padding-top").map(Number.AtLeast(parseInt(c.handleCSS.height,10))).px().first()}.append(d))};a=function(a,c){var b,d,e,i,c=Object.Extend({change:Function.Empty,backgroundColor:"#fff",barColor:"rgba(0,128,0,0.5)",textColor:"white",reset:!1},c);b=f(a).addClass("progress-bar");i=0;c.reset&&(d=b.css("background").first(),
e=b.css("color").first());return b.zap("updateProgress",function(a){for(;1<a;)a/=100;i=a;1===a&&c.reset?b.css("background",d).css("color",e):b.css({background:"-webkit-gradient(linear, 0 0, "+parseInt(100*a)+"% 0, color-stop(0, "+c.barColor+"), color-stop(0.98, "+c.barColor+"), color-stop(1.0, "+c.backgroundColor+"))",color:c.textColor});if(Object.IsFunc(c.change))return c.change(i)})};i=function(a,c){var b,d,c=Object.Extend({exclusive:!1,sticky:!1},c);d=f(a).addClass("accordion");b=function(a){var b,
e,g,a=f(a).children().first().filter("*");if(2!==a.len())throw Exception("accordion row requires 2 elements, not "+a.len());g=a.eq(0).addClass("title");b=a.eq(1).addClass("body").hide();e=!1;return g.click(function(){c.exclusive&&d.find(".body").hide();if(e){if(c.sticky)return b.show().addClass("visible"),g.addClass("selected").trigger("select"),e=!0;b.hide().removeClass("visible");g.removeClass("selected").trigger("deselect");return e=!1}b.show().addClass("visible");g.addClass("selected").trigger("select");
return e=!0})};d.bind("DOMNodeInserted",function(a){var c;c=d.children().first().filter("*");a=f(a.target).parents().first();return b(a.intersect(c))});d.children().first().filter("*").map(b);return d};b=function(a){var c,b,d;b=f(a).css({position:"relative",top:"0px",left:"0px"}.hide().map(f));c=0;b[c].show();b.next=function(){b[c].hide();c=++c%nn;return b[c].show()};b.activate=function(a){b[c].hide();c=a;return b[a].show()};a=0;for(d=b.len();0<=d?a<d:a>d;0<=d?a++:a--)b[a].zap("_viewIndex",a.zap("activate",
function(){return b.activate(this._viewIndex)}));return b};c=function(a,c){var b,d,e;e=f(a);c=f(c).viewStack();d=e.len();for(b=0;0<=d?b<=d:b>=d;0<=d?b++:b--)e._tabIndex=b;f(e[0]).addClass("active");return e.click(function(){e.removeClass("active");c.activate(this._tabIndex);return f(this).addClass("active")})};return{name:"UI",$:{UI:{Draggable:d,ProgressBar:a,ViewStack:b,Tabs:c,Accordion:i}},dialog:function(a){return e(this,a)},progressBar:function(b){return a(this,b)},viewStack:function(a){return b(this,
a)},tabs:function(a){return c(this,a)},accordion:function(a){return i(this,a)},draggable:function(a){return d(this,a)}}})})(Bling);
(function(f){return f.plugin(function(){var i,e,d,a,c,b,g,h,j,l,s,m,k,n,o,r;s=/!==|!=|!|\#|\%|\%=|\&|\&\&|\&\&=|&=|\*|\*=|\+|\+=|-|-=|->|\.{1,3}|\/|\/=|:|::|;|<<=|<<|<=|<|===|==|=|>>>=|>>=|>=|>>>|>>|>|\?|@|\[|\]|}|{|\^|\^=|\^\^|\^\^=|\|=|\|\|=|\|\||\||~/g;j=/\b[Ff]unction\b|\bvar\b|\.prototype\b|\.__proto__\b|\bString\b|\bArray\b|\bNumber\b|\bObject\b|\bbreak\b|\bcase\b|\bcontinue\b|\bdelete\b|\bdo\b|\bif\b|\belse\b|\bfinally\b|\binstanceof\b|\breturn\b|\bthrow\b|\btry\b|\btypeof\b|\btrue\b|\bfalse\b/g;i=
/\d+\.*\d*/g;e=/\$(\(|\.)/g;r=/\t/g;k=/\/\/.*?(?:\n|$)/;l=/\/\*(?:.|\n)*?\*\//;a=function(a){return a?"<span class='com'>"+a+"</span>":""};m=function(a){return a?"<span class='str'>"+a+"</span>":""};b=function(a,b){var c,d;c=a.indexOf('"',b);d=a.indexOf("'",b);-1===c&&(c=a.length);-1===d&&(d=a.length);return c===d?[null,-1]:c<d?['"',c]:["'",d]};d=function(a,c,b){for(c=a.indexOf(b,c);"\\"===a.charAt(c-1)&&0<c&&c<a.length;)c=a.indexOf(b,c+1);return c};o=function(a){var c,e,g,h,j;c=0;g=a.length;j=[];
if(!Object.IsString(a))if(Object.IsFunction(a.toString))a=a.toString(),g=a.length;else throw TypeError("invalid string argument to split_quoted");for(;c<g;){h=b(a,c);e=h[1];if(-1===e){j.push(a.substring(c));break}j.push(a.substring(c,e));c=d(a,e+1,h[0]);if(-1===c)throw Error("unclosed quote: "+h[0]+" starting at "+e);j.push(a.substring(e,c+1));c+=1}return j};c=function(a){var c;c=a.match(k);a=a.match(l);return c===a?[-1,null]:null===c&&null!==a?[a.index,a[0]]:null!==c&&null===a?[c.index,c[0]]:a.index<
c.index?[a.index,a[0]]:[c.index,c[0]]};n=function(a){var b,d,e,g,h,j;h=[];b=0;for(e=a.length;b<e;)if(j=a.substring(b),g=c(j),d=g[0],-1<d)h.push(j.substring(0,d)),h.push(g[1]),b+=d+g[1].length;else{h.push(j);break}return h};g=function(a,c){return a.replace(s,"<span class='opr'>$&</span>").replace(i,"<span class='num'>$&</span>").replace(j,"<span class='kwd'>$&</span>").replace(e,"<span class='bln'>$$</span>$1").replace(r,"&nbsp;&nbsp;")+m(c)};h=function(c,b){return f(o(c)).fold(g).join("")+a(b)};return{name:"PrettyPrint",
$:{prettyPrint:function(a,c){var b,d;Object.IsFunction(a)&&(a=a.toString());if(!Object.IsString(a))throw TypeError("prettyPrint requires a function or string to format, not '"+Object.Type(a)+"'");if(0===f("style#prettyPrint").length){d="code.pp .bln { font-size: 17px; } ";c=Object.Extend({opr:"#880",str:"#008",com:"#080",kwd:"#088",num:"#808",bln:"#800"},c);for(b in c)d+="code.pp ."+b+" { color: "+c[b]+"; } ";f.synth("style#prettyPrint").text(d).appendTo("head")}return"<code class='pp'>"+f(n(a)).fold(h).join("")+
"</code>"}}}})})(Bling);
(function(){var f=Object.prototype.hasOwnProperty,i=function(e,d){function a(){this.constructor=e}for(var c in d)f.call(d,c)&&(e[c]=d[c]);a.prototype=d.prototype;e.prototype=new a;e.__super__=d.prototype;return e};(function(e){e.plugin(function(){return{name:"StateMachine",$:{StateMachine:function(){function d(a){this.reset();this.table=a;Object.defineProperty(this,"modeline",{get:this.table[this._mode]});Object.defineProperty(this,"mode",{set:function(a){var b;this._lastMode=this._mode;this._mode=
a;if(this._mode!==this._lastMode&&null!=this.modeline&&"enter"in this.modeline)for(b=this.modeline.enter.call(this);Object.IsFunction(b);)b=b.call(this);return a},get:function(){return this._mode}})}d.prototype.reset=function(){return this._lastMode=this._mode=null};d.prototype.GO=function(a){return function(){return this.mode=a}};d.GO=function(a){return function(){return this.mode=a}};d.prototype.run=function(a){var c,b,d,e,j,f;e=this.mode=0;for(j=a.length;e<j;e++){c=a[e];d=this.modeline;null==d?
b=null:c in d?b=d[c]:"def"in d&&(b=d.def);for(;Object.IsFunction(b);)b=b.call(this,c)}if(Object.IsFunction(null!=(f=this.modeline)?f.eof:void 0))b=this.modeline.eof.call(this);for(;Object.IsFunction(b);)b=b.call(this);this.reset();return this};return d}()}}});return e.plugin(function(){var d;d=function(){function a(){a.__super__.constructor.call(this,a.STATE_TABLE);this.fragment=this.parent=document.createDocumentFragment()}i(a,e.StateMachine);a.STATE_TABLE=[{enter:function(){this.tag=this.id=this.cls=
this.attr=this.val=this.text="";this.attrs={};return this.GO(1)}},{'"':a.GO(6),"'":a.GO(7),"#":a.GO(2),".":a.GO(3),"[":a.GO(4)," ":a.GO(9),"+":a.GO(11),",":a.GO(10),def:function(a){return this.tag+=a},eof:a.GO(13)},{".":a.GO(3),"[":a.GO(4)," ":a.GO(9),"+":a.GO(11),",":a.GO(10),def:function(a){return this.id+=a},eof:a.GO(13)},{enter:function(){if(0<this.cls.length)return this.cls+=" "},"#":a.GO(2),".":a.GO(3),"[":a.GO(4)," ":a.GO(9),"+":a.GO(11),",":a.GO(10),def:function(a){return this.cls+=a},eof:a.GO(13)},
{"=":a.GO(5),"]":function(){this.attrs[this.attr]=this.val;return this.GO(1)},def:function(a){return this.attr+=a},eof:a.GO(12)},{"]":function(){this.attrs[this.attr]=this.val;return this.GO(1)},def:function(a){return this.val+=a},eof:a.GO(12)},{'"':a.GO(8),def:function(a){return this.text+=a},eof:a.GO(12)},{"'":a.GO(8),def:function(a){return this.text+=a},eof:a.GO(12)},{enter:function(){this.emitText();return this.GO(0)}},{enter:function(){this.emitNode();return this.GO(0)}},{enter:function(){this.emitNode();
this.parent=null;return this.GO(0)}},{enter:function(){var a;this.emitNode();this.parent=null!=(a=this.parent)?a.parentNode:void 0;return this.GO(0)}},{enter:function(){return e.log("Error in synth expression: "+this.input)}},{enter:function(){this.tag.length&&this.emitNode();if(this.text.length)return this.emitText()}}];a.prototype.emitNode=function(){var a,b;b=document.createElement(this.tag);b.id=this.id||null;b.className=this.cls||null;for(a in this.attrs)b.setAttribute(a,this.attrs[a]);this.parent.appendChild(b);
return this.parent=b};a.prototype.emitText=function(){this.parent.appendChild(e.HTML.parse(this.text));return this.text=""};return a}();return{name:"Synth",$:{synth:function(a){var c;c=new d;c.run(a);return 1===c.fragment.childNodes.length?e(c.fragment.childNodes[0]):e(c.fragment)}}}})})(Bling)}).call(this);
(function(){var f=Object.prototype.hasOwnProperty,i=function(e,d){function a(){this.constructor=e}for(var c in d)f.call(d,c)&&(e[c]=d[c]);a.prototype=d.prototype;e.prototype=new a;e.__super__=d.prototype;return e};(function(e){var d,a;d={};e.plugin(function(){var a,b;a=null;d={};b={register_engine:function(b,e){d[b]=e;if(null==a)return a=b},render:function(b,e){if(a in d)return d[a](b,e)}};b.__defineSetter__("engine",function(b){if(!b in d)throw Error("invalid template engine: "+b+" not one of "+
Object.Keys(d));return a=b});b.__defineGetter__("engine",function(){return a});return{name:"Template",$:{template:b}}});e.template.register_engine("null",function(){return function(a){return a}}());a=function(a,b,d,e,j){var f,i,m;null==j&&(j=-1);f=1;0>j&&(j=a.length+1+j);for(i=e;e<=j?i<j:i>j;e<=j?i++:i--)if(m=a[i],m===d?f+=1:m===b&&(f-=1),0===f)return i;return-1};e.template.register_engine("pythonic",function(){var c,b,d;d=/([0-9#0+-]*)\.*([0-9#+-]*)([diouxXeEfFgGcrsqm])((?:.|\n)*)/;c=/%[\(\/]/;b=
function(b){var e,f,i,m,k,n,o,b=b.split(c);k=b.length;o=[b[0]];for(f=i=1;1<=k?f<k:f>k;1<=k?f++:f--){e=a(b[f],")","(",0,-1);if(-1===e)return"Template syntax error: unmatched '%(' starting at: "+b[f].substring(0,15);m=b[f].substring(0,e);n=b[f].substring(e);e=d.exec(n);if(null===e)return"Template syntax error: invalid type specifier starting at '"+n+"'";n=e[4];o[i++]=m;o[i++]=e[1]|0;o[i++]=e[2]|0;o[i++]=e[3];o[i++]=n}return o};b.cache={};return function(a,c){var d,e,g,f,i,o,r,p,t,q,u;d=b.cache[a];null==
d&&(d=b.cache[a]=b(a));o=[d[0]];f=1;e=d.length;g=1;for(u=e-5;g<=u;g+=5){p=d.slice(g,g+4+1||9E9);i=p[0];r=p[1];e=p[2];t=p[3];p=p[4];q=c[i];null==q&&(q="missing value: "+i);switch(t){case "d":o[f++]=""+parseInt(q,10);break;case "f":o[f++]=parseFloat(q).toFixed(e);break;case "s":o[f++]=""+q;break;default:o[f++]=""+q}0<r&&(o[f]=String.PadLeft(o[f],r));o[f++]=p}return o.join("")}}());return e.template.register_engine("js-eval",function(){(function(){function a(){a.__super__.constructor.apply(this,arguments)}
i(a,e.StateMachine);a.STATE_TABLE=[{enter:function(){this.data=[];return this.GO(1)}},{}];return a})();return function(a){return a}}())})(Bling)}).call(this);
(function(f){return f.plugin(function(){var i,e,d;d=function(a){var c,b,d,h;c=a.indexOf(":");if(0<c)return d=parseInt(a.slice(0,c),10),b=a.slice(c+1,c+1+d),h=a[c+1+d],a=a.slice(c+d+2),b=function(){switch(h){case "#":return Number(b);case "'":return""+b;case "!":return"true"===b;case "~":return null;case "]":return i(b);case "}":return e(b)}}(),[b,a]};i=function(a){var c,b;for(c=[];0<a.length;)a=d(a),b=a[0],a=a[1],c.push(b);return c};e=function(a){var c,b,e;for(c={};0<a.length;)e=d(a),b=e[0],a=e[1],
a=d(a),e=a[0],a=a[1],c[b]=e;return c};return{name:"TNET",$:{TNET:{stringify:function(a){var c,b,d;d=function(){switch(Object.Type(a)){case "number":return[""+a,"#"];case "string":return[a,"'"];case "function":return[""+a,"'"];case "boolean":return[""+!!a,"!"];case "null":return["","~"];case "undefined":return["","~"];case "array":return[function(){var c,d,e;e=[];c=0;for(d=a.length;c<d;c++)b=a[c],e.push(f.TNET.stringify(b));return e}().join(""),"]"];case "object":return[function(){var c;c=[];for(b in a)c.push(f.TNET.stringify(b)+
f.TNET.stringify(a[b]));return c}().join(""),"}"]}}();c=d[0];return(c.length|0)+":"+c+d[1]},parse:function(a){var c;return null!=(c=d(a))?c[0]:void 0}}}}})})(Bling);
(function(f){return f.plugin(function(){var i,e,d,a,c,b;e=function(a,b){var c,b=Object.Extend({autoOpen:!1,draggable:!0},b);c=f(a).addClass("dialog");b.draggable&&c.draggable();b.autoOpen&&c.show().center();c.find("button.close, .close-button").bind("click touchstart",function(){c.hide();return!1});return c};d=function(a,b){var c,d,e,i,k,b=Object.Extend({handleCSS:{}},b);b.handleCSS=Object.Extend({position:"absolute",top:"0px",left:"0px",width:"100%",height:"6px"},b.handleCSS);c=f(a);e=!1;i=k=0;d=
f.synth("div.handle").defaultCss({background:"-webkit-gradient(linear, 50% 0%, 50% 100%, from(#eee), color-stop(0.25, #bbb), color-stop(0.3, #eee), color-stop(0.5, #eee), to(#bbb))",height:"6px","border-radius":"3px",cursor:"move"}.css(b.handleCSS.bind("mousedown, touchstart",function(a){e=!0;i||(i=a.pageX);k||(k=a.pageY);return!1})));f(document.bind("mousemove, touchmove",function(a){var b;if(e)return b=a.pageX-i,a=a.pageY-k,c.transform({translate:[b,a]},0).trigger("drag",{dragObject:c}),!1})).bind("mouseup, touchend",
function(){var a;if(e)return e=!1,a=d.position()[0],f(document.elementFromPoint(a.left,a.top-1).trigger("drop",{dropObject:c}))});return c.addClass("draggable").css({position:"relative","padding-top":c.css("padding-top").map(Number.AtLeast(parseInt(b.handleCSS.height,10))).px().first()}.append(d))};a=function(a,b){var c,d,e,i,b=Object.Extend({change:Function.Empty,backgroundColor:"#fff",barColor:"rgba(0,128,0,0.5)",textColor:"white",reset:!1},b);c=f(a).addClass("progress-bar");i=0;b.reset&&(d=c.css("background").first(),
e=c.css("color").first());return c.zap("updateProgress",function(a){for(;a>1;)a=a/100;i=a;a===1&&b.reset?c.css("background",d).css("color",e):c.css({background:"-webkit-gradient(linear, 0 0, "+parseInt(a*100)+"% 0, color-stop(0, "+b.barColor+"), color-stop(0.98, "+b.barColor+"), color-stop(1.0, "+b.backgroundColor+"))",color:b.textColor});if(Object.IsFunc(b.change))return b.change(i)})};i=function(a,b){var c,d,b=Object.Extend({exclusive:!1,sticky:!1},b);d=f(a).addClass("accordion");c=function(a){var c,
e,g,a=f(a).children().first().filter("*");if(2!==a.len())throw Exception("accordion row requires 2 elements, not "+a.len());g=a.eq(0).addClass("title");c=a.eq(1).addClass("body").hide();e=!1;return g.click(function(){b.exclusive&&d.find(".body").hide();if(e){if(b.sticky)return c.show().addClass("visible"),g.addClass("selected").trigger("select"),e=!0;c.hide().removeClass("visible");g.removeClass("selected").trigger("deselect");return e=!1}c.show().addClass("visible");g.addClass("selected").trigger("select");
return e=!0})};d.bind("DOMNodeInserted",function(a){var b;b=d.children().first().filter("*");a=f(a.target).parents().first();return c(a.intersect(b))});d.children().first().filter("*").map(c);return d};b=function(a){var b,c,d;c=f(a).css({position:"relative",top:"0px",left:"0px"}.hide().map(f));b=0;c[b].show();c.next=function(){c[b].hide();b=++b%nn;return c[b].show()};c.activate=function(a){c[b].hide();b=a;return c[a].show()};a=0;for(d=c.len();0<=d?a<d:a>d;0<=d?a++:a--)c[a].zap("_viewIndex",a.zap("activate",
function(){return c.activate(this._viewIndex)}));return c};c=function(a,b){var c,d,e;e=f(a);b=f(b).viewStack();d=e.len();for(c=0;0<=d?c<=d:c>=d;0<=d?c++:c--)e._tabIndex=c;f(e[0]).addClass("active");return e.click(function(){e.removeClass("active");b.activate(this._tabIndex);return f(this).addClass("active")})};return{name:"UI",$:{UI:{Draggable:d,ProgressBar:a,ViewStack:b,Tabs:c,Accordion:i}},dialog:function(a){return e(this,a)},progressBar:function(b){return a(this,b)},viewStack:function(a){return b(this,
a)},tabs:function(a){return c(this,a)},accordion:function(a){return i(this,a)},draggable:function(a){return d(this,a)}}})})(Bling);
(function(){var f=Array.prototype.slice;$.plugin(function(){var i,e,d,a,c,b,g,h,j,l,s,m;h="px,pt,pc,em,%,in,cm,mm,ex,".split(",");i=/(\d+\.*\d*)(px|pt|pc|em|%|in|cm|mm|ex)/;b=function(a){return i.exec(a)[2](i.test(a)?void 0:"")};a=function(b,c){return a[b][c]()};g=function(a){return function(){return a}};j=0;for(s=h.length;j<s;j++){e=h[j];l=0;for(m=h.length;l<m;l++)d=h[l],(a[e]||(a[e]={}))[d]=g(+(e===d||""===e||""===d))}a["in"].pt=function(){return 72};a["in"].px=function(){return 96};a["in"].cm=
function(){return 2.54};a.pc.pt=function(){return 12};a.cm.mm=function(){return 10};a.em.px=function(){var a,b;b=$("<span style='font-size:1em;visibility:hidden'>x</span>").appendTo("body");a=b.width().first();b.remove();return a};a.ex.px=function(){var a,b;b=$("<span style='font-size:1ex;visibility:hidden'>x</span>").appendTo("body");a=b.width().first();b.remove();return a};a.ex.em=function(){return 2};e=function(){var b,c,d,e,f,i;i=[];e=0;for(f=h.length;e<f;e++)b=h[e],i.push(function(){var e,f,
i;i=[];e=0;for(f=h.length;e<f;e++)c=h[e],!a(b,c)&&a(c,b)&&(console.log("found inverse: "+b+"."+c),a[b][c]=g(1/a(c,b))),i.push(function(){var e,f,i;i=[];f=0;for(e=h.length;f<e;f++){d=h[f];if(!a(b,d)&&a(b,c)&&a(c,d)){console.log("found induction: "+b+"."+d);i.push(a[b][d]=g(a(b,c)*a(c,d)))}else i.push(void 0)}return i}());return i}());return i};e();e();$.assert("10cm"===parseFloat("300px")*a[b("300px")].cm()+"cm");c=function(a,b){var c,d,e;e=[];c=0;for(d=b.length;0<=d?c<d:c>d;0<=d?c++:c--)e.push(b[c]=
convertTo(a,b[c]));return e};Object.Type.register("units",{match:function(a){return i.test(a)}});e=function(a){return function(){var d,e;d=1<=arguments.length?f.call(arguments,0):[];c(e=b(this[0]),this);return a.apply(this,d)+e}};return{min:e(function(){return this.reduce(function(a){return Math.min(parseFloat(this),a)})}),max:e(function(){return this.reduce(function(a){return Math.max(parseFloat(this),a)})}),sum:e(function(){return this.reduce(function(a){return parseFloat(this)+a})}),mean:e(function(){return parseFloat(this.sum())/
this.length}),magnitude:e(function(){return Math.sqrt(this.floats().squares().sum())}),squares:function(){return this.map(function(){var a;return(a=parseFloat(this))*a})},scale:function(a){return this.map(function(){return a*parseFloat(this)})},add:function(a){return this.map(function(){return a+this})},normalize:function(){return this.scale(1/this.magnitude())}}})}).call(this);
$.plugin(function(){var f,i,e,d;f=function(){return"EOF"};for(d=0;1E3>d;d++)i=d;e=0;return function(a){a=extend({item:function(){return f},action:Function.Identity,latency:10},a);return extend(new $.EventEmitter,{run:function(){var c,b=this;c=function(){var d;if((d=a.action(a.item()))!==f)return b.emit("data",d),setTimeout(c,a.latency)};return setTimeout(c,a.latency)}})}({item:function(){return i[e++](e<i.length?void 0:f)},action:function(a){return a*a-1},latency:10}).on("data",function(a){return console.log("data:",
a.on("error",function(a){return console.log("error:",a.run())}))})});
