Function.prototype.inheritsFrom=function(d){this.prototype=new d;return this.prototype.constructor=this};function isType(d,f){return!d?f===d:typeof f==="string"?d.__proto__.constructor.name==f:d.__proto__.constructor===f}function isSubtype(d,f){return d==undefined?d==f:d.__proto__==undefined?false:d.__proto__.constructor==f?true:isSubtype(d.__proto__,f)}function isString(d){return typeof d=="string"||isSubtype(d,String)}function isNumber(d){return isFinite(d)}
function isFunc(d){return typeof d=="function"||isType(d,Function)}function isNode(d){return d?d.nodeType>0:false}function isFragment(d){return d?d.nodeType==11:false}function isArray(d){return Object.prototype.toString.call(d)=="[object Array]"||isSubtype(d,Array)}function isObject(d){return typeof d=="object"}function hasValue(d){return d!=undefined&&d!=null}
Function.prototype.bound=function(d,f){var h=this,j=function(){return h.apply(d,f?f:arguments)};j.toString=function(){return"bound-method of "+d+"."+h.name+"(...) { [code] }"};return j};Function.Empty=function(){};Function.NotNull=function(d){return d!=null};Function.NotUndefined=function(d){return d!=undefined};Function.NotNullOrUndefined=function(d){return d!=undefined&&d!=null};Function.IndexFound=function(d){return d>-1};
Function.HtmlEscape=function(d){return d.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\t/g,"&nbsp;&nbsp;")};Function.ReduceAnd=function(d){return d&&this};
function Bling(d,f){if(isBling(d))return d;if(this===window||this===Bling)return new Bling(d,f);f=f||document;if(d==undefined)Bling.__init__(this,[]);else if(typeof d=="string")if(d[0]=="<")Bling.__init__(this,[Bling.HTML.parse(d)]);else if(isBling(f)){Bling.__init__(this,[]);var h=this;f.each(function(){Bling.__copy__(h,this.querySelectorAll(d))})}else if(f.querySelectorAll!=undefined)Bling.__init__(this,f.querySelectorAll(d));else throw Error("invalid context "+f+")");else if(typeof d=="number")Array.call(this,
d);else if(d===window||isNode(d))Bling.__init__(this,[d]);else d.length!=undefined?Bling.__init__(this,d):Bling.__init__(this,[d])}Bling.inheritsFrom(Array);function isBling(d){return d&&d.__bling__||isType(d,Bling)}Bling.__copy__=function(d,f,h){var j=0;for(h=h?Math.min(f.length,h):f.length;j<h;j++)d.push(f[j])};Bling.__init__=function(d,f){Array.call(d,f.length);Bling.__copy__(d,f);d.__bling__=true};Bling.operator=Bling;
Bling.extend=function(d,f,h){for(var j in f)if(h&&d[j]!=undefined)for(var m in h)d[j][m]=f[j][m];else d[j]=f[j];return d};Bling.addMethods=function(){for(var d=0,f=arguments.length;d<f;d++){var h=arguments[d];if(isFunc(h)){if(!h.name)throw Error("cannot extend with an anonymous method");Bling.prototype[h.name]=h}else Bling.extend(Bling.prototype,h)}};
Bling.addGlobals=function(){for(var d=0,f=arguments.length;d<f;d++){var h=arguments[d];if(isFunc(h)){if(!h.name)throw Error("cannot extend with an anonymous method");Bling[h.name]=h}else Bling.extend(Bling,h)}};
(function(){function d(a){for(var b=a.cloneNode(),c=0;c<a.childNodes.length;c++)b.appendChild(d(a.childNodes[c])).parentNode=b;return b}function f(a){return function(b){return isFunc(b)?this.bind(a,b):this.trigger(a,b?b:[])}}function h(a,b){throw Error("sql error ["+b.code+"] "+b.message);}function j(a,b,c){var e=a.find(".buttons");if(e.length==0)e=a.append("<div class='buttons'></div>").find(".buttons");b=b||"undefined";b=b.replace(/_/g," ");return $("<button>"+b+"</button>").bind("click",c.bound(a)).appendTo(e)}
Bling.addGlobals({timeoutQueue:new (function(){this.queue=[];this.next=function(){this.queue.length>0&&this.queue.shift()()}.bound(this);this.schedule=function(a,b){if(isFunc(a)){var c=this.queue.length;a.order=b+(new Date).getTime();if(c==0||a.order>this.queue[c-1].order)this.queue[c]=a;else for(var e=0;e<c;e++)this.queue[e].order>a.order&&this.queue.splice(e,0,a);setTimeout(this.next,b)}}}),dumpText:function(a,b,c){var e="";c=c||{};b=b||"";if(typeof a=="object"){if(c[a])return"{..circular ref..}";
c[a]=true;e="{\n";b+="\t";for(var g in a){var i=undefined;try{i=a[g]}catch(k){console.log(g,k)}i=isNode(i)?i.toString():Bling.dumpText(Bling.dumpText(i,b,c));e+=b+g+": "+i+",\n"}b=b.slice(1);e+=b+"}"}else if(typeof a=="string"){if(a.length>250)a=a.substring(0,250)+"...";e+=a[0]!='"'?'"'+a+'"':a}else if(typeof a=="function"){if(c[a])return"{..circular ref..}";c[a]=true;a=""+a;e+=a.slice(0,a.indexOf("{")+1)+" ... }"}else e+=""+a;return e},dumpHtml:function(a){return Bling.dumpText(a).replace(/(?:\r|\n)+/g,
"<br>").replace(/\t/g,"&nbsp;&nbsp;")}});Bling.addMethods({each:function(a){this.forEach(function(b){a.call(b,b)});return this},map:function(a){var b=new Bling(this.length);this.each(function(c){try{b.push(a.call(c,c))}catch(e){if(isType(e,TypeError))b.push(a(c));else throw e;}});return b},reduce:function(a,b){if(!a)return this;var c=b,e=this;if(!hasValue(b)){c=this[0];e=this.skip(1)}e.each(function(){c=a.call(this,c,this)});return c},filter:function(a){for(var b=new Bling(this.length),c=0,e=this.length;c<
e;c++){var g=this[c];a.call(g,g)&&b.push(g)}return b},distinct:function(){var a={};this.each(function(){a[this]=1});var b=new Bling;for(var c in a)b.push(c);return b},zip:function(){function a(l){var o=l.indexOf(".");return o>-1?this.zip(l.substr(0,o)).zip(l.substr(o+1)):this.map(function(){var p=this[l];return isFunc(p)?p.bound(this):p})}switch(arguments.length){case 0:return this;case 1:return a.call(this,arguments[0]);default:for(var b={},c=new Bling,e=0,g=arguments.length;e<g;e++){if(b[e]==undefined)b[e]=
[];b[e]=a.call(this,arguments[e])}e=0;for(g=this.length;e<g;e++){var i={};for(var k in b)i[k]=b[k].shift();c.push(i)}return c}},zap:function(a,b){if(!a)return this;var c=a.indexOf(".");return c>-1?this.zip(a.substr(0,c)).zap(a.substr(c+1),b):isArray(b)?this.each(function(e){e[a]=b[++c]}):this.each(function(){this[a]=b})},take:function(a){a=a||1;a=Math.min(a,this.length);for(var b=new Bling(a),c=0;c<a;c++)b.push(this[c]);return b},skip:function(a){a=a||1;for(var b=new Bling(Math.max(0,this.length-
a)),c=0,e=this.length-a;c<e;c++)b.push(this[c+a]);return b},last:function(a){return a?this.skip(Math.max(0,this.length-a)):this[this.length-1]},first:function(a){return a?this.take(a):this[0]},join:function(a){if(this.length==0)return"";return this.reduce(function(b){return b+a+this})},slice:function(a,b){var c=this.length;b=b==undefined?c:b<0?c+b:b;a=a==undefined?c:a<0?c+a:a;return this.take(b).skip(a)},concat:function(a){for(var b=0,c=a.length;b<c;b++)this.push(a[b]);return this},weave:function(a){for(var b=
a.length,c=this.length,e=new Bling(c+b),g=c-1;g>=0;g--)e[g*2+1]=this[g];for(g=0;g<b;g++)e[g*2]=a[g];e.length=c+b;return e},fold:function(a){var b=this.length;if(b<2)return this;for(var c=new Bling(b/2),e=0;e<b-1;e+=2)c.push(a.call(this,this[e],this[e+1]));return c},call:function(){return this.apply(null,arguments)},apply:function(a,b){return this.map(function(){if(isFunc(this))return this.apply(a,b);return this})},toString:function(){return"Bling{["+this.map(function(){return this.toString()}).join(", ")+
"]}"},future:function(a,b){b&&Bling.timeoutQueue.schedule(b.bound(this),a);return this},fork:function(a){this.future(0,a.bound(this.clone()));return this},log:function(a){a?console.log(a,this,this.length+" items"):console.log(this,this.length+" items");return this}});Bling.addMethods({floats:function(){return this.map(function(){if(isBling(this))return this.floats();return parseFloat(this)})},ints:function(){return this.map(function(){if(isBling(this))return this.ints();return parseInt(this)})},min:function(){return this.reduce(function(a){if(isBling(this))return this.min();
return Math.min(this,a)})},max:function(){return this.reduce(function(a){if(isBling(this))return this.max();return Math.max(this,a)})},average:function(){return this.sum()/this.length},sum:function(){return this.reduce(function(a){if(isBling(this))return a+this.sum();return a+this})},squares:function(){return this.map(function(){if(isBling(this))return this.squares();return this*this})},magnitude:function(){return this.map(function(){if(isBling(this))return this.magnitude();return Math.sqrt(this.squares().sum())})},
scale:function(a){return this.map(function(){if(isBling(this))return this.scale(a);return a*this})},normalize:function(){return this.scale(1/this.magnitude())}});var m=function(a,b){a&&b&&a.parentNode.insertBefore(b,a)},n=function(a){a=isNode(a)?a:isBling(a)?a.toFragment():isString(a)?(new Bling(a)).toFragment():isFunc(a.toString)?(new Bling(a.toString())).toFragment():undefined;Bling.nextguid=Bling.nextguid||1;if(a.guid==undefined)a.guid=Bling.nextguid++;return a};Bling.addGlobals({HTML:{parse:function(a){var b=
document.createElement("div");b.innerHTML=a;a=document.createDocumentFragment();for(var c=0,e=b.childNodes.length;c<e;c++)a.appendChild(b.removeChild(b.childNodes[0]));return e==1?a.removeChild(a.childNodes[0]):a},stringify:function(a){a=d(a);var b=document.createElement("div");b.appendChild(a);var c=b.innerHTML;b.removeChild(a);a.parentNode=null;return c}}});Bling.addMethods({html:function(a){return a==undefined?this.zip("innerHTML"):isString(a)?this.zap("innerHTML",a):isBling(a)?this.html(a.toFragment()):
isNode(a)?this.each(function(){for(this.replaceChild(this.childNodes[0],a);this.childNodes.length>1;)this.removeChild(this.childNodes[1])}):undefined},append:function(a){a=n(a);this.zip("appendChild").take(1).call(a);this.zip("appendChild").skip(1).each(function(){this(d(a))});return this},appendTo:function(a){(new Bling(a)).append(this);return this},prepend:function(a){a=n(a);this.take(1).each(function(){m(this.childNodes[0],a)});this.skip(1).each(function(){m(this.childNodes[0],d(a))});return this},
prependTo:function(a){(new Bling(a)).prepend(this);return this},before:function(a){a=n(a);this.take(1).each(function(){m(this,a)});this.skip(1).each(function(){m(this,d(a))});return this},after:function(a){a=n(a);this.take(1).each(function(){this.parentNode.insertBefore(a,this.nextSibling)});this.skip(1).each(function(){this.parentNode.insertBefore(d(a),this.nextSibling)});return this},wrap:function(a){a=n(a);if(isFragment(a))throw Error("cannot wrap something with a fragment");return this.map(function(b){if(isFragment(b))a.appendChild(b);
else if(isNode(b)){var c=b.parentNode;if(c){var e=document.createElement("dummy");a.appendChild(c.replaceChild(e,b));c.replaceChild(a,e)}else a.appendChild(b)}return b})},unwrap:function(){return this.each(function(){this.parentNode&&this.parentNode.parentNode&&this.parentNode.parentNode.replaceChild(this,this.parentNode)})},attr:function(a,b){var c=this.zip(b?"setAttribute":"getAttribute").call(a,b);return b?this:c},addClass:function(a){return this.removeClass(a).each(function(){var b=this.className.split(" ").filter(function(c){return c&&
c!=""});b.push(a);this.className=b.join(" ")})},removeClass:function(a){var b=function(c){return c!=a};return this.each(function(){this.className.split(" ").filter(b).join(" ")})},toggleClass:function(a){var b=function(c){return c!=a};return this.each(function(c){var e=c.className.split(" ");c.className=e.indexOf(a)>-1?e.filter(b).join(" "):e.push(a).join(" ")})},hasClass:function(a){this.zip("className.split").call(" ").zip("indexOf").call(a).map(Function.IndexFound)},text:function(a){return a?this.zap("innerText",
a):this.zip("innerText")},val:function(a){return a?this.zap("value",a):this.zip("value")},css:function(a,b){if(hasValue(b)||isObject(a)){var c=this.zip("style.setProperty");if(isString(a))c.call(a,b);else for(var e in a)c.call(e,a[e]);return this}c=this.map(window.getComputedStyle).zip("getPropertyValue").call(a);return this.zip("style").zip(a).weave(c).fold(function(g,i){return g?g:i})},width:function(a){return this.css("width",a)},height:function(a){return this.css("height",a)},center:function(a){a=
a||"viewport";var b=document.body.clientHeight/2,c=document.body.clientWidth/2;return this.each(function(){var e=$(this),g=parseFloat(e.height().first()),i=parseFloat(e.width().first());i=a=="viewport"||a=="horizontal"?document.body.scrollLeft+c-i/2:NaN;y=a=="viewport"||a=="vertical"?document.body.scrollTop+b-g/2:NaN;e.css({position:"absolute",left:isNumber(i)?i+"px":undefined,top:isNumber(y)?y+"px":undefined})})},trueColor:function(a,b){function b(c){c[0]+=(this[0]-c[0])*this[3];c[1]+=(this[1]-c[1])*
this[3];c[2]+=(this[2]-c[2])*this[3];c[3]=Math.min(1,c[3]+this[3]);return c}a=a||"background-color";return this.parents().map(function(){return this.map(window.getComputedStyle).filter(hasValue).zip("getPropertyValue").call(a).filter(isString).toColors().reverse().reduce(b,new Bling([0,0,0,0])).toRGBAString()})},toColors:function(){if(this.length==0)return this;return this.map(function(){if(isString(this)){var a=document.createElement("div");a.style.color=this;if(a=a.style.getPropertyValue("color")){a=
a.slice(a.indexOf("(")+1,a.indexOf(")")).split(", ");if(a.length==3)a[3]=1;return(new Bling(a)).floats()}}})},toRGBAString:function(){if(this.length==0)return this;return this.length==4?"rgba("+this.join(", ")+")":this.length==3?"rgb("+this.join(", ")+")":undefined},child:function(a){return this.map(function(){return this.childNodes[a]})},children:function(){return this.map(function(){return new Bling(this.childNodes)})},parent:function(){return this.zip("parentNode")},parents:function(){return this.map(function(){for(var a=
$([]),b=this.parentNode;b;){a.push(b);b=b.parentNode}return a})},remove:function(){return this.each(function(){this.parentNode&&this.parentNode.removeChild(this)})},find:function(a){return this.map(function(){return new Bling(a,this)}).reduce(function(b){return b.concat(this)})},clone:function(){return this.map(d)},toFragment:function(){if(this.length==1)return n(this[0]);var a=document.createDocumentFragment();this.map(n).map(a.appendChild.bound(a));return a}});Bling.addGlobals({ready:function(a){(new Bling(window)).bind("load",
a)}});Bling.addMethods({bind:function(a,b){return this.each(function(){this.addEventListener(a,b)})},once:function(a,b){var c=function(e){b.call(this,e);this.unbind(a,c)};return this.bind(a,c)},cycle:function(a){var b=0,c=arguments.slice(1,arguments.length);return this.bind(a,function(e){c[b].call(this,e);b=b++%c.length})},unbind:function(a,b){return this.each(function(){this.removeEventListener(a,b)})},trigger:function(a,b){var c=undefined;b=Bling.extend({bubbles:true,cancelable:true},b);switch(a){case "click":case "mousemove":case "mousedown":case "mouseup":case "mouseover":case "mouseout":c=
document.createEvent("MouseEvents");b=Bling.extend({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,button:0,relatedTarget:null},b);c.initMouseEvent(a,b.bubbles,b.cancelable,window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);break;case "blur":case "focus":case "reset":case "submit":case "abort":case "change":case "load":case "unload":c=document.createEvent("UIEvents");c.initUIEvent(a,
b.bubbles,b.cancelable,window,1);break;case "touchstart":case "touchmove":case "touchend":case "touchcancel":c=document.createEvent("TouchEvents");b=Bling.extend({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,touches:[],targetTouches:[],changedTouches:[],scale:1,rotation:0},b);c.initTouchEvent(a,b.bubbles,b.cancelable,window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.touches,b.targetTouches,
b.changedTouches,b.scale,b.rotation);break;case "gesturestart":case "gestureend":case "gesturecancel":c=document.createEvent("GestureEvents");b=Bling.extend({detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,target:null,scale:1,rotation:0},b);c.initGestureEvent(a,b.bubbles,b.cancelable,window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.target,b.scale,b.rotation);break;case "drag":case "drop":case "selection":case "cut":case "copy":case "paste":case "orientationchange":default:c=
document.createEvent("Events");c.initEvent(a,b.bubbles,b.cancelable)}return c?this.each(function(){this.dispatchEvent(c);c.result=c.returnValue=undefined}):this},click:f("click"),mousemove:f("mousemove"),mousedown:f("mousedown"),mouseup:f("mouseup"),mouseover:f("mouseover"),mouseout:f("mouseout"),blur:f("blur"),focus:f("focus"),load:f("load"),ready:f("load"),unload:f("unload"),reset:f("reset"),submit:f("submit"),change:f("change"),abort:f("abort"),cut:f("cut"),copy:f("copy"),paste:f("paste"),selection:f("selection"),
drag:f("drag"),drop:f("drop"),orientationchange:f("orientationchange"),touchstart:f("touchstart"),touchmove:f("touchmove"),touchend:f("touchend"),touchcancel:f("touchcancel"),gesturestart:f("gesturestart"),gestureend:f("gestureend"),gesturecancel:f("gesturecancel")});Bling.addGlobals({duration:function(a){var b={slow:700,medium:500,normal:300,fast:100}[a];return b?b:parseFloat(a)}});Bling.addMethods({transform:function(a,b,c){if(typeof b=="function"){c=b;b=undefined}b=b||"normal";var e=Bling.duration(b);
b=[];var g="",i={};for(var k in a)if(/(?:scale|translate|rotate|scale3d|translateX|translateY|translateZ|translate3d|rotateX|rotateY|rotateZ|rotate3d)/.test(k)){var l=a[k];if(l.join)l=l.join(", ");else if(l.toString)l=l.toString();g+=" "+k+"("+l+")"}else i[k]=a[k];for(k in i)b.push(k);g&&b.push("-webkit-transform");this.css("-webkit-transition-property",b.join(", "));this.css("-webkit-transition-duration",b.map(function(){return e+"ms"}).join(", "));for(k in i)this.css(k,i[k]);g&&this.css("-webkit-transform",
g);return this.future(e,c)},hide:function(a){var b=this.each(function(){this._display=this.style.display=="none"?undefined:this.style.display;this.style.display="none"});a&&a.call(this);return b},show:function(a){return this.each(function(){this.style.display=this._display?this._display:"block";this._display=undefined}).future(50,a)},toggle:function(a){return this.each(function(){var b=$(this).css("display").first();if(b=="none")if(this._display!=undefined){this.style.display=this._display;this._display=
undefined}else this.style.display="block";else{this._display=b;this.style.display="none"}a&&a.call(this)})},fadeIn:function(a,b){return this.css("opacity","0.0").show(function(){this.transform({opacity:"1.0",translate3d:[0,0,0]},a,b)})},fadeOut:function(a,b,c,e){c=c||0;e=e||0;return this.each(function(g){$(g).transform({opacity:"0.0",translate3d:[c,e,0]},a,function(){this.hide()})}).future(Bling.duration(a),b)},fadeLeft:function(a,b){return this.fadeOut(a,b,"-"+this.width().first(),0)},fadeRight:function(a,
b){return this.fadeOut(a,b,this.width().first(),0)},fadeUp:function(a,b){return this.fadeOut(a,b,0,"-"+this.height().first())},fadeDown:function(a,b){return this.fadeOut(a,b,0,this.height().first())}});Bling.addGlobals({db:function(a,b,c,e){return new Bling([window.openDatabase(a||"bling.db",b||"1.0",c||"bling database",e||1024)])}});Bling.addMethods({transaction:function(a){this.zip("transaction").call(a);return this},sql:function a(a,b,c,e){if(a!=undefined){if(typeof b=="function"){e=c;c=b;b=undefined}b=
b||[];c=c||Function.Empty;e=e||h;assert(isType(this[0],"Database"),"can only call .sql() on a bling of Database");return this.transaction(function(g){g.executeSql(a,b,c,e)})}}});var q=function(a){var b=[];a=JSON.parse(JSON.stringify(a));for(var c in a)b.push(c+"="+escape(a[c]));return b.join("&")};Bling.addGlobals({http:function(a,b){var c=new XMLHttpRequest;if(isFunc(b))b={success:b.bound(c)};b=Bling.extend({method:"GET",data:null,state:Function.Empty,success:Function.Empty,error:Function.Empty,
async:true,withCredentials:false},b);b.state=b.state.bound(c);b.success=b.success.bound(c);b.error=b.error.bound(c);if(b.data&&b.method=="GET")a+="?"+q(b.data);else if(b.data&&b.method=="POST")b.data=q(b.data);c.open(b.method,a,b.async);c.withCredentials=b.withCredentials;c.onreadystatechange=function(){b.state&&b.state();if(c.readyState==4)if(c.status==200)b.success(c.responseText);else b.error&&b.error(c.status,c.statusText)};c.send(b.data);return new Bling([c])},post:function(a,b){if(isFunc(b))b=
{success:b};b=b||{};b.method="POST";return Bling.http(a,b)},get:function(a,b){if(isFunc(b))b={success:b};b=b||{};b.method="GET";return Bling.http(a,b)}});Bling.addMethods(function(){var a=0,b=arguments.length,c="create";if(isString(arguments[0])){c=arguments[0];a++}if("create"==c){if(this.isDialog)return this;c=$("<div class='dialog' style='display:none'/>");c.isDialog=true;this.wrap(c);c.contentNode=c[0].childNodes[0];for(a==b&&j(c,"OK",function(){this.hide()});a<b;a++){var e=arguments[a];if(!(e==
null||isString(e)))if(isFunc(e))j(c,e.name,e);else for(var g in e)isFunc(e[g])&&j(c,g,e[g])}c[0].parentNode==null&&c.appendTo("body");a=c.css("top").first();b=c.css("left").first();return c.css("position","absolute").css("top",a).css("left",b)}else if("destroy"==c){if(!this.isDialog)throw Error("dialog expected");this.isDialog=false;return $(this.contentNode).unwrap()}})})();$=Bling.operator;
